import {oauthRoute} from '../worker/social/oauth.mjs';
import {hash} from '../worker/social/core.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {socialAPI} from '../worker/social/api.mjs';
import {createBracket,result,nextRound,standings} from '../worker/social/brackets.mjs';
import {mp4Duration} from '../worker/social/media.mjs';
import {mediaRoute} from '../worker/social/media.mjs';
import {networkRoute} from '../worker/social/network.mjs';
import {authRoute} from '../worker/social/auth.mjs';
import {communityRoute} from '../worker/social/community.mjs';
test('network presence, literal matching, friendship permissions and inbox isolation',async()=>{
 const database=db(),env={SOCIAL_DB:database};
 const people=['rainsoranked','Beta_Player','ThirdPlayer'].map((handle,i)=>({id:'network-'+i,handle,status:'active',role:'player'}));
 for(const p of people){database.sqlite.prepare('INSERT INTO users(id,handle,password_hash,salt,recovery_hash,created_at) VALUES(?,?,?,?,?,?)').run(p.id,p.handle,'','','','2026-09-29');database.sqlite.prepare("INSERT INTO profiles(user_id,display_name,presence) VALUES(?,?,'online')").run(p.id,p.handle);}
 const [a,b,c]=people;
 const req=(path,method='GET',value)=>new Request('https://social.example/api/social'+path,{method,headers:{'Content-Type':'application/json'},...(value?{body:JSON.stringify(value)}:{})});
 const call=(path,method='GET',value,user=null)=>networkRoute(req(path,method,value),env,path.split('?')[0],user);
 assert.equal((await call('/presence')).count,0);
 assert.equal((await call('/presence','POST',{},a)).count,1);
 assert.equal((await call('/players')).items[0].handle,'rainsoranked');
 assert.equal((await call('/players?q=Rai')).items[0].presence,'online');
 assert.deepEqual((await call('/players?q=%25')).items,[]);
 assert.deepEqual((await call('/players?q=_')).items.map(p=>p.handle),['Beta_Player']);
 database.sqlite.prepare('UPDATE chat_presence SET seen_at=0').run();assert.equal((await call('/presence')).count,0);
 database.sqlite.prepare("UPDATE profiles SET presence='offline' WHERE user_id=?").run(a.id);await call('/presence','POST',{},a);assert.equal((await call('/presence')).count,0);
 await call('/friends','POST',{handle:b.handle,action:'request'},a);
 await assert.rejects(()=>call('/friends','POST',{handle:b.handle,action:'accept'},a),e=>e.status===403);
 await call('/friends','POST',{handle:a.handle,action:'accept'},b);
 assert.equal((await call('/friends','GET',null,a)).items[0].friendship,'accepted');
 assert.equal((await call('/friends','GET',null,c)).items.length,0);
 for(const [sender,channel,content] of [[a,'dm:'+b.handle,'private hello'],[a,'global','public hello'],[b,'global','public reply']])await communityRoute(req('/messages','POST',{channel,content}),env,'/messages',sender);
 assert.equal((await call('/conversations','GET',null,b)).items[0].content,'private hello');
 assert.equal((await call('/conversations','GET',null,c)).items.length,0);
 const chat=await call('/chat');assert.deepEqual(chat.items.map(m=>m.content),['public hello','public reply']);assert.equal(chat.unread,2);
 assert.equal((await call('/chat?after='+chat.cursor)).unread,0);
 database.sqlite.prepare('INSERT INTO blocks VALUES(?,?)').run(b.id,a.id);
 assert.equal((await call('/conversations','GET',null,b)).items.length,0);
 assert.deepEqual((await call('/chat','GET',null,b)).items.map(m=>m.content),['public reply']);
 await assert.rejects(()=>call('/friends','POST',{handle:a.handle,action:'request'},b),e=>e.status===403);
 const search=await communityRoute(req('/search?q=%25'),env,'/search',null);assert.deepEqual(search.players,[]);
 database.sqlite.close();
});
test('profile validates customization and image ownership; GIF upload preserves animation bytes',async()=>{
 const database=db(),objects=new Map(),user={id:'custom-profile',handle:'CustomPlayer',status:'active'};
 database.sqlite.prepare('INSERT INTO users(id,handle,password_hash,salt,recovery_hash,created_at) VALUES(?,?,?,?,?,?)').run(user.id,user.handle,'','','','2026-09-29');database.sqlite.prepare('INSERT INTO profiles(user_id,display_name) VALUES(?,?)').run(user.id,user.handle);
 const env={SOCIAL_DB:database,MEDIA:{async put(id,b){objects.set(id,b);},async get(id){return {body:objects.get(id)};}}};
 const gif=Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7','base64');
 const saved=await mediaRoute(new Request('https://social.example/api/social/media',{method:'POST',body:gif}),env,'/media',user);
 const font=Buffer.alloc(28);font.writeUInt32BE(0x10000);font.writeUInt16BE(1,4);font.write('name',12);font.writeUInt32BE(28,20);const uploadedFont=await mediaRoute(new Request('https://social.example/api/social/media?kind=font',{method:'POST',body:font}),env,'/media',user);
 const base={display_name:'My name',color:'#F02040',font:'standard',font_url:uploadedFont.url,country:'us',presence:'online',avatar:saved.url};
 const update=value=>authRoute(new Request('https://social.example/api/social/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}),env,'/profile',user);
 await update(base);const p=database.sqlite.prepare('SELECT * FROM profiles WHERE user_id=?').get(user.id);assert.equal(p.country,'US');assert.equal(p.color,'#F02040');assert.equal(p.font_url,base.font_url);
 const image=await mediaRoute(new Request('https://social.example'+saved.url),env,saved.url.replace('/api/social',''),null);assert.equal(image.headers.get('Content-Type'),'image/gif');assert.deepEqual(Buffer.from(await image.arrayBuffer()),gif);
 for(const value of [{color:'red;background:url(evil)'},{font_url:'javascript:alert(1)'},{font_url:'https://example.com/style.css'},{country:'1!'},{avatar:'/api/social/media/11111111-1111-1111-1111-111111111111'}])await assert.rejects(()=>update({...base,...value}),e=>e.status===400);
 const publicFont=await mediaRoute(new Request('https://social.example'+uploadedFont.url),env,uploadedFont.url.replace('/api/social',''),null);assert.equal(publicFont.headers.get('Content-Type'),'font/ttf');
 await assert.rejects(()=>mediaRoute(new Request('https://social.example/api/social/media?kind=font',{method:'POST',body:gif}),env,'/media',user),e=>e.status===400);
 const group=await communityRoute(new Request('https://social.example/api/social/groups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({handle:'MyCrew',name:'My Crew',privacy:'Public'})}),env,'/groups',user);
 const picture=(who,url)=>communityRoute(new Request('https://social.example/api/social/groups/'+group.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({avatar:url})}),env,'/groups/'+group.id,who);
 await assert.rejects(()=>picture({id:'outsider',status:'active'},saved.url),e=>e.status===403);
 await assert.rejects(()=>picture(user,uploadedFont.url),e=>e.status===400);
 await picture(user,saved.url);assert.equal(database.sqlite.prepare('SELECT avatar FROM groups WHERE id=?').get(group.id).avatar,saved.url);
 await update({...base,avatar:'',font_url:'',country:''});const crewImage=await mediaRoute(new Request('https://social.example'+saved.url),env,saved.url.replace('/api/social',''),null);assert.equal(crewImage.status,200);database.sqlite.close();
});
const makePlayers=n=>Array.from({length:n},(_,i)=>({id:'p'+i,name:'Player '+i,handle:'player'+i,seed:i+1}));
test('media uploads require login, persist bytes, respect visibility and reject excess size',async()=>{
 const database=db(),objects=new Map(),user={id:'media-test',status:'active'};
 database.sqlite.prepare("INSERT INTO users(id,handle,password_hash,salt,recovery_hash,created_at) VALUES(?,?,?,?,?,?)").run(user.id,'MediaTest','','','','2026-09-29');
 database.sqlite.prepare('INSERT INTO profiles(user_id,display_name) VALUES(?,?)').run(user.id,'Media Test');
 const env={SOCIAL_DB:database,MEDIA:{async put(key,bytes){objects.set(key,bytes.slice());},async get(key){return objects.has(key)?{body:objects.get(key)}:null;}}};
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX2kAAAAASUVORK5CYII=','base64');
 const upload=(bytes=png)=>new Request('https://social.example/api/social/media',{method:'POST',body:bytes});
 await assert.rejects(()=>mediaRoute(upload(),env,'/media',null),e=>e.status===401);
 await assert.rejects(()=>mediaRoute(upload(),env,'/media',{...user,status:'muted'}),e=>e.status===403);
 const saved=await mediaRoute(upload(),env,'/media',user),path=saved.url.replace('/api/social','');
 const get=new Request('https://social.example'+saved.url);
 await assert.rejects(()=>mediaRoute(get,env,path,null),e=>e.status===404);
 const own=await mediaRoute(get,env,path,user);assert.equal(own.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await own.arrayBuffer()),png);
 database.sqlite.prepare('UPDATE profiles SET avatar=? WHERE user_id=?').run(saved.url,user.id);
 assert.equal((await mediaRoute(get,env,path,null)).status,200);
 await assert.rejects(()=>mediaRoute(upload(new Uint8Array(4*1024*1024+1)),env,'/media',user),e=>e.status===413);
 await assert.rejects(()=>mediaRoute(upload(Buffer.from('<script>invalid</script>')),env,'/media',user),e=>e.status===400);
 assert.equal(objects.size,1);database.sqlite.close();
});
function db(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../worker/social/migrations/0001_social.sql',import.meta.url),'utf8'));sqlite.exec(readFileSync(new URL('../worker/social/migrations/0002_discovery.sql',import.meta.url),'utf8'));sqlite.exec(readFileSync(new URL('../worker/social/migrations/0003_network.sql',import.meta.url),'utf8'));sqlite.exec(readFileSync(new URL('../worker/social/migrations/0004_oauth.sql',import.meta.url),'utf8'));sqlite.exec(readFileSync(new URL('../worker/social/migrations/0005_google_oauth.sql',import.meta.url),'utf8'));const adapter={prepare(sql){let args=[];return {bind(...v){args=v;return this;},async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){return {meta:{changes:sqlite.prepare(sql).run(...args).changes}};}};},async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}},sqlite};return adapter;}
test('single elimination completes with exactly one champion for 2–32 entrants',()=>{for(let n=2;n<=32;n++){let s=createBracket(makePlayers(n),'Single Elimination');let played=0;while(!s.completed){const m=s.matches.find(x=>x.status==='Ready');assert.ok(m,`stalled at ${n}`);s=result(s,m.id,{a:2,b:0});played++;}assert.equal(played,n-1);assert.ok(s.champion);assert.equal(standings(s).reduce((a,p)=>a+p.losses,0),n-1);}});
test('double elimination requires two losses and handles final reset',()=>{for(const n of [2,3,4,5,8,12,16])for(const reset of [false,true]){let s=createBracket(makePlayers(n),'Double Elimination'),count=0;while(!s.completed){const m=s.matches.find(x=>x.status==='Ready');assert.ok(m,`stalled at ${n}`);s=result(s,m.id,{a:reset&&m.id==='GF'?0:2,b:reset&&m.id==='GF'?2:0});assert.ok(++count<2*n+5);}const stats=standings(s);for(const p of stats)assert.equal(p.losses,p.id===s.champion?(reset?1:0):2,`${n} ${p.id}`);assert.equal(s.matches.some(m=>m.id==='RESET'),reset);}});
test('overriding upstream result clears dependent completed results',()=>{let s=createBracket(makePlayers(4),'Single Elimination');s=result(s,'W1-0',{a:1,b:0});s=result(s,'W1-1',{a:1,b:0});s=result(s,'W2-0',{a:1,b:0});assert.equal(s.completed,true);s=result(s,'W1-0',{a:0,b:1});assert.equal(s.completed,false);assert.equal(s.matches.find(m=>m.id==='W2-0').status,'Ready');assert.deepEqual(s.matches.find(m=>m.id==='W2-0').scores,[]);});
test('round robin pairs every player exactly once over complete cycle',()=>{const s=createBracket(makePlayers(6),'Round Robin',{rounds:5});const pairs=s.matches.map(m=>m.players.slice().sort().join(','));assert.equal(pairs.length,15);assert.equal(new Set(pairs).size,15);});
test('Swiss pairs new opponents and awards byes without fabricating played matches',()=>{let s=createBracket(makePlayers(5),'Swiss',{rounds:3});for(let round=1;round<=3;round++){for(const m of [...s.matches].filter(m=>m.status==='Ready'))s=result(s,m.id,{a:1,b:0});if(round<3)s=nextRound(s);}assert.equal(s.completed,true);const pairs=s.matches.filter(m=>!m.bye).map(m=>m.players.slice().sort().join(','));assert.equal(new Set(pairs).size,pairs.length);assert.equal(s.matches.filter(m=>m.bye).length,3);});
test('FFA validates a whole lobby, scores, and advances top players',()=>{let s=createBracket(makePlayers(12),'Free For All',{rounds:3,lobbySize:12,advance:4});assert.throws(()=>result(s,s.matches[0].id,{results:[]}));s=result(s,s.matches[0].id,{results:s.players.map((p,i)=>({id:p.id,placement:i+1,eliminations:12-i,score:0}))});s=nextRound(s);assert.equal(s.matches.at(-1).players.length,4);assert.deepEqual(s.matches.at(-1).players,['p0','p1','p2','p3']);});
test('MP4 validator rejects untrusted metadata, invalid files and incomplete containers',()=>{for(const bytes of [new Uint8Array(0),new TextEncoder().encode('45 seconds'),new Uint8Array([0,0,0,12,109,111,111,102,0,0,0,0])])assert.throws(()=>mp4Duration(bytes));});
test('social storage, permissions, registrations and community integration',async t=>{const database=db(),env={SOCIAL_DB:database},origin='https://social.example';const admin={id:'owner',handle:'owner',role:'administrator',status:'active'};let seq=0;
 async function req(path,method='GET',data,token='',asAdmin=false){const response=await socialAPI(new Request(origin+'/api/social'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'test-'+seq++,...(token?{Authorization:'Bearer '+token}:{})},...(data===undefined?{}:{body:JSON.stringify(data)})}),env,asAdmin?admin:null);return {status:response.status,data:await response.json()};}
 let a,b,tournament;
 await t.test('reserved handles and weak passwords rejected',async()=>{assert.equal((await req('/signup','POST',{handle:'admin',password:'a strong password'})).status,400);assert.equal((await req('/signup','POST',{handle:'PlayerOne',password:'short'})).status,400);});
 await t.test('signup, login and case insensitive uniqueness',async()=>{a=(await req('/signup','POST',{handle:'PlayerOne',password:'a strong password 1'})).data;b=(await req('/signup','POST',{handle:'PlayerTwo',password:'a strong password 2'})).data;assert.ok(a.token&&a.recovery);assert.equal((await req('/signup','POST',{handle:'playerone',password:'a strong password 3'})).status,409);assert.ok((await req('/login','POST',{handle:'PLAYERONE',password:'a strong password 1'})).data.token);assert.equal((await req('/login','POST',{handle:'PLAYERONE',password:'a wrong password'})).status,401);assert.equal((await req('/session','GET',undefined,a.token)).data.user.handle,'PlayerOne');assert.equal('password_hash' in a.user,false);});
 const event={title:'Integration Cup',slug:'integration-cup',game:'Halo',format:'Single Elimination',status:'Draft',start:'2026-10-01T18:00:00Z',registration:'Open',max:2,min:2};
 await t.test('players cannot create tournaments, drafts are private',async()=>{assert.equal((await req('/tournaments','POST',event,a.token)).status,403);const r=await req('/tournaments','POST',event,'',true);assert.equal(r.status,200);tournament=r.data;assert.equal((await req('/tournaments/'+tournament.id)).status,404);assert.deepEqual((await req('/tournaments')).data.items,[]);assert.equal((await req('/tournaments/'+tournament.id,'PUT',{...event,status:'Registration Open',revision:1},'',true)).status,200);assert.equal((await req('/tournaments/'+tournament.id,'PUT',{...event,status:'Registration Open',revision:1},'',true)).status,409);});
 await t.test('registration persists and blocks duplicates and excess capacity',async()=>{for(const p of [a,b])assert.equal((await req('/tournaments/'+tournament.id+'/register','POST',{},p.token)).status,200);assert.equal((await req('/tournaments/'+tournament.id+'/register','POST',{},a.token)).status,409);const c=(await req('/signup','POST',{handle:'PlayerThree',password:'a strong password 3'})).data;assert.equal((await req('/tournaments/'+tournament.id+'/register','POST',{},c.token)).status,409);});
 await t.test('bracket writes need role and revision, results produce public standings',async()=>{const path='/tournaments/'+tournament.id+'/bracket';assert.equal((await req(path,'POST',{action:'generate'},a.token)).status,403);const r=await req(path,'POST',{action:'generate'},'',true);assert.equal(r.status,200);let s=r.data.bracket;assert.equal(s.matches.length,1);assert.equal((await req(path,'POST',{action:'result',match:'W1-0',a:2,b:1,revision:s.revision-1},'',true)).status,409);const next=await req(path,'POST',{action:'result',match:'W1-0',a:2,b:1,revision:s.revision},'',true);assert.equal(next.status,200);assert.equal(next.data.bracket.completed,true);const publicData=(await req('/tournaments/'+tournament.id)).data;assert.equal(publicData.standings[0].wins,1);assert.equal(database.sqlite.prepare('SELECT count(*) n FROM matches').get().n,1);});
 let post,group;
 await t.test('posts persist, likes toggle, authors cannot delete another player post',async()=>{post=(await req('/posts','POST',{content:'Hello @PlayerTwo'},a.token)).data.id;assert.ok(post);assert.equal((await req('/posts')).data.items.length,1);assert.equal((await req('/posts/'+post,'DELETE',undefined,b.token)).status,403);assert.equal((await req('/posts/'+post+'/like','POST',{},b.token)).data.liked,true);assert.equal((await req('/posts/'+post+'/like','POST',{},b.token)).data.liked,false);assert.equal((await req('/notifications','GET',undefined,b.token)).data.items.some(n=>n.text.includes('mentioned')),true);});
 await t.test('private groups and chat are protected server-side',async()=>{group=(await req('/groups','POST',{name:'Private Crew',handle:'privatecrew',privacy:'Invite Only',description:'Private group'},a.token)).data.id;const p=await req('/posts','POST',{content:'Secret tactics',group_id:group},a.token);assert.equal(p.status,200);assert.equal((await req('/posts?group='+group)).data.items.length,0);assert.equal((await req('/posts/'+p.data.id,'GET',undefined,b.token)).status,404);assert.equal((await req('/messages?channel=group:'+group,'GET',undefined,b.token)).status,403);assert.equal((await req('/groups/'+group,'POST',{action:'join'},b.token)).status,400);assert.equal((await req('/groups/'+group,'POST',{action:'invite',handle:'PlayerTwo'},a.token)).status,200);assert.equal((await req('/groups/'+group,'POST',{action:'join'},b.token)).status,200);assert.equal((await req('/posts?group='+group,'GET',undefined,b.token)).data.items.length,1);});
 await t.test('DM channels are private and blocks work both directions',async()=>{assert.equal((await req('/messages','POST',{channel:'dm:PlayerTwo',content:'Hello'},a.token)).status,200);assert.equal((await req('/messages?channel=dm:PlayerOne','GET',undefined,b.token)).data.items.length,1);assert.equal((await req('/messages?channel=dm:anything','GET',undefined,b.token)).status,403);await req('/block','POST',{handle:'PlayerOne'},b.token);assert.equal((await req('/messages','POST',{channel:'dm:PlayerTwo',content:'Blocked'},a.token)).status,403);});
 await t.test('reports stay private and moderation revokes sessions',async()=>{assert.equal((await req('/reports','POST',{target_type:'post',target_id:post,reason:'Spam',detail:'Review'},b.token)).status,200);assert.equal((await req('/moderation','GET',undefined,b.token)).status,403);assert.equal((await req('/moderation','POST',{action:'ban',target:'PlayerOne'},'',true)).status,200);assert.equal((await req('/session','GET',undefined,a.token)).data.user,null);assert.equal((await req('/login','POST',{handle:'PlayerOne',password:'a strong password 1'})).status,403);});
 database.sqlite.close();});

test('Discord sign-in binds callback and browser verifier, consumes once, and never claims existing handles',async()=>{
 const database=db(),env={SOCIAL_DB:database,DISCORD_CLIENT_ID:'client',DISCORD_CLIENT_SECRET:'test-secret',OAUTH_BASE_URL:'https://social.example'};
 const call=(path,method='GET',b,user=null,headers={})=>oauthRoute(new Request('https://social.example/api/social'+path,{method,headers:{'Content-Type':'application/json',...headers},...(b?{body:JSON.stringify(b)}:{})}),env,path.split('?')[0],user);
 assert.deepEqual(await oauthRoute(new Request('https://social.example/api/social/oauth/providers'),{SOCIAL_DB:database},'/oauth/providers',null),{providers:[]});
 const verifier='a'.repeat(64),flow=await call('/oauth/begin','POST',{challenge:await hash(verifier)});
 const start=await call('/oauth/start?state='+flow.state);assert.equal(start.status,302);assert.match(start.headers.get('Set-Cookie'),/Secure; HttpOnly; SameSite=Lax/);assert.equal(new URL(start.headers.get('Location')).searchParams.get('scope'),'identify');
 await assert.rejects(()=>call('/oauth/callback?state='+flow.state+'&code=test'),e=>e.status===403);
 await assert.rejects(()=>call('/oauth/complete','POST',{state:flow.state,verifier:'b'.repeat(64)}),e=>e.status===401);
 assert.equal((await call('/oauth/complete','POST',{state:flow.state,verifier})).pending,true);
 const original=globalThis.fetch;
 try{globalThis.fetch=async url=>Response.json(String(url).endsWith('/token')?{access_token:'test-token'}:{id:'123456789012345678'});
 const callback=await call('/oauth/callback?state='+flow.state+'&code=test','GET',null,null,{'Cookie':'__Host-xbt-oauth='+flow.state});assert.equal(callback.status,200);
 }finally{globalThis.fetch=original;}
 assert.equal((await call('/oauth/complete','POST',{state:flow.state,verifier})).needsHandle,true);
 const signed=await call('/oauth/complete','POST',{state:flow.state,verifier,handle:'DiscordPlayer'});assert.ok(signed.token);assert.equal(signed.user.handle,'DiscordPlayer');
 await assert.rejects(()=>call('/oauth/complete','POST',{state:flow.state,verifier}),e=>e.status===401);
 const second=await call('/oauth/begin','POST',{challenge:await hash(verifier)});database.sqlite.prepare('UPDATE oauth_flows SET subject=? WHERE state_hash=?').run('987654321098765432',await hash(second.state));
 await assert.rejects(()=>call('/oauth/complete','POST',{state:second.state,verifier,handle:'DiscordPlayer'}),e=>e.status===409);
 const linking=await call('/oauth/begin','POST',{challenge:await hash(verifier),link:true},signed.user);database.sqlite.prepare('UPDATE oauth_flows SET subject=? WHERE state_hash=?').run('123456789012345678',await hash(linking.state));
 await assert.rejects(()=>call('/oauth/complete','POST',{state:linking.state,verifier}),e=>e.status===401);
 assert.equal((await call('/oauth/complete','POST',{state:linking.state,verifier},signed.user)).user.id,signed.user.id);
 database.sqlite.close();
});

test('Google uses a distinct provider, PKCE and verified UserInfo without merging matching provider subjects',async()=>{
 const database=db(),env={SOCIAL_DB:database,GOOGLE_CLIENT_ID:'google-client',GOOGLE_CLIENT_SECRET:'google-secret',OAUTH_BASE_URL:'https://social.example'};
 const call=(path,method='GET',b,headers={})=>oauthRoute(new Request('https://social.example/api/social'+path,{method,headers:{'Content-Type':'application/json',...headers},...(b?{body:JSON.stringify(b)}:{})}),env,path.split('?')[0],null);
 assert.deepEqual((await call('/oauth/providers')).providers,['Google']);
 await assert.rejects(()=>call('/oauth/begin','POST',{provider:'discord',challenge:'a'.repeat(64)}),e=>e.status===503);
 const verifier='c'.repeat(64),flow=await call('/oauth/begin','POST',{provider:'google',challenge:await hash(verifier)});
 const authorize=new URL((await call('/oauth/start?state='+flow.state)).headers.get('Location'));
 assert.equal(authorize.origin,'https://accounts.google.com');assert.equal(authorize.searchParams.get('scope'),'openid profile');assert.equal(authorize.searchParams.get('code_challenge_method'),'S256');assert.match(authorize.searchParams.get('redirect_uri'),/oauth\/google\/callback$/);
 const flowRow=database.sqlite.prepare('SELECT * FROM oauth_flows WHERE state_hash=?').get(await hash(flow.state));assert.equal(authorize.searchParams.get('code_challenge'),Buffer.from(await hash(flowRow.provider_verifier),'hex').toString('base64url'));
 const cookie={'Cookie':'__Host-xbt-oauth='+flow.state};await assert.rejects(()=>call('/oauth/callback?state='+flow.state+'&code=google','GET',null,cookie),e=>e.status===403);
 const original=globalThis.fetch;try{globalThis.fetch=async(url,options)=>{if(String(url)==='https://oauth2.googleapis.com/token'){assert.equal(options.body.get('code_verifier'),flowRow.provider_verifier);assert.equal(options.body.get('client_id'),'google-client');return Response.json({access_token:'google-token'});}assert.equal(String(url),'https://openidconnect.googleapis.com/v1/userinfo');assert.equal(options.headers.Authorization,'Bearer google-token');return Response.json({sub:'123456789012345678',name:'Ignored provider name'});};await call('/oauth/google/callback?state='+flow.state+'&code=google','GET',null,cookie);}finally{globalThis.fetch=original;}
 const signed=await call('/oauth/complete','POST',{state:flow.state,verifier,handle:'GooglePlayer'});assert.ok(signed.token);assert.equal(database.sqlite.prepare('SELECT provider FROM oauth_identities WHERE user_id=?').get(signed.user.id).provider,'google');
 // Identical provider subject strings never grant access to another provider's identity.
 env.DISCORD_CLIENT_ID='discord-client';env.DISCORD_CLIENT_SECRET='discord-secret';const other=await call('/oauth/begin','POST',{provider:'discord',challenge:await hash(verifier)});database.sqlite.prepare('UPDATE oauth_flows SET subject=? WHERE state_hash=?').run('123456789012345678',await hash(other.state));assert.equal((await call('/oauth/complete','POST',{state:other.state,verifier})).needsHandle,true);
 database.sqlite.close();
});
