import {api,state,$,$$,esc,identity,avatar,title,empty,field,submit,signed,signIn,toast,report,poll} from './core.js?v=20260930-v2-final';
import {nameMarkup,flag} from './identity.js?v=20260930-v2-final';
const plane='<svg viewBox="0 0 24 24" width="21" height="21" aria-hidden="true"><path d="M3 3 22 12 3 21 6 13 15 12 6 11Z" fill="currentColor"/></svg>';
function bubble(m){return `<article class="chat-message ${m.user_id===state.user?.id?'mine':''}">${avatar(m)}<div class="chat-bubble"><a href="/social/@${esc(m.handle)}" data-route>${nameMarkup(m)} <span class="chat-country">${flag(m.country)}</span></a><p>${esc(m.content)}</p><div class="chat-meta"><time datetime="${esc(m.created_at)}">${new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time><button data-report-chat="${esc(m.id)}" aria-label="Report message by ${esc(m.display_name)}">···</button></div></div></article>`;}
function composer(){return `<form class="chat-composer"><label class="sr-only">Message<input name="content" placeholder="Type a message…" maxlength="1500" required autocomplete="off"></label><button type="submit" aria-label="Send message">${plane}</button></form>`;}
function bindReports(root){root.addEventListener('click',e=>{const b=e.target.closest('[data-report-chat]');if(b)report('message',b.dataset.reportChat);});}
export function mountChat(){
 const root=$('#right-rail');let open=matchMedia('(min-width:1151px)').matches,seen=0,initialized=false,busy=false,lastMarkup='',session=0;
 try{const saved=localStorage.getItem('xbt-chat-open');if(saved!==null)open=saved!=='0';}catch{}
 root.innerHTML=`<section class="chatroom"><button class="chat-heading" aria-controls="chat-body" aria-expanded="true"><span><b class="rgb-title">Global Chat</b><small id="online-count">Connecting…</small></span><span class="chat-unread" hidden></span><span class="chat-toggle-icon">−</span></button><div id="chat-body"><div class="chat-members" id="chat-members"></div><div class="chat-log" role="log" aria-label="Public chat messages" aria-live="polite"></div><div class="chat-status" role="status"></div><div class="composer-slot"></div></div></section>`;
 const log=$('.chat-log',root),badge=$('.chat-unread',root),heading=$('.chat-heading',root);
 const key=()=> 'xbt-chat-seen-'+(state.user?.id||'guest');
 const save=()=>{try{localStorage.setItem(key(),String(seen));}catch{}};
 function acknowledge(){if(open&&!document.hidden&&log.scrollTop+log.clientHeight>=log.scrollHeight-50){seen=Number(root.dataset.cursor)||seen;save();badge.hidden=true;}}
 function toggle(){root.classList.toggle('chat-closed',!open);$('#chat-body').hidden=!open;heading.setAttribute('aria-expanded',String(open));$('.chat-toggle-icon',root).textContent=open?'−':'+';try{localStorage.setItem('xbt-chat-open',open?'1':'0');}catch{}if(open){log.scrollTop=log.scrollHeight;acknowledge();}}
 heading.onclick=()=>{open=!open;toggle();};log.onscroll=acknowledge;
 function setup(){session++;initialized=false;lastMarkup='';log.innerHTML='';seen=0;try{seen=Number(localStorage.getItem(key()))||0;}catch{}const slot=$('.composer-slot',root);slot.innerHTML=state.user?composer():'<button class="chat-signin button" type="button">SIGN IN TO CHAT </button>';if(!state.user){$('.chat-signin',root).onclick=()=>signIn();}else submit($('form',slot),async(b,f)=>{await api('/messages',{method:'POST',body:{channel:'global',content:b.content}});f.reset();await load();log.scrollTop=log.scrollHeight;acknowledge();});toggle();}
 async function presence(){const version=session;try{const d=await api('/presence',state.user&&!document.hidden?{method:'POST',body:{}}:{});if(version!==session)return;$('#online-count').textContent=d.count+' online';$('#chat-members').innerHTML=d.items.slice(0,8).map(p=>`<a href="/social/@${esc(p.handle)}" data-route title="${esc(p.display_name)} · ${esc(p.presence)}">${avatar(p)}</a>`).join('')||'<small>No players online yet</small>';}catch{$('#online-count').textContent='Connection interrupted';}}
 async function load(){if(busy||document.hidden)return;busy=true;const version=session;try{const d=await api('/chat?after='+seen);if(version!==session)return;const near=log.scrollTop+log.clientHeight>=log.scrollHeight-50,html=d.items.map(bubble).join('')||'<p class="chat-empty">The lobby is yours.<br>Say hello to the community.</p>';root.dataset.cursor=d.cursor;if(html!==lastMarkup){log.innerHTML=html;lastMarkup=html;if(near||!initialized)log.scrollTop=log.scrollHeight;}if(!initialized&&!seen){seen=d.cursor;save();}initialized=true;badge.textContent=d.unread>99?'99+':String(d.unread);badge.hidden=!d.unread;acknowledge();$('.chat-status',root).textContent='';}catch(e){$('.chat-status',root).textContent='Chat reconnecting…';}finally{busy=false;}}
 bindReports(root);setup();presence();load();setInterval(load,4000);setInterval(()=>{if(!document.hidden)presence();},30000);
 addEventListener('xbt-session',()=>{setup();presence();load();});addEventListener('xbt-profile',()=>{setup();presence();load();});document.addEventListener('visibilitychange',()=>{if(!document.hidden){presence();load();}});
}
export async function messages(root){
 if(!state.user){root.innerHTML=title('YOUR NETWORK','MESSAGES')+empty('YOUR DIRECT MESSAGES','Sign in to start a private conversation.','<button class="button" id="dm-signin">SIGN IN</button>');$('#dm-signin',root).onclick=()=>signIn();return;}
 const params=new URLSearchParams(location.search),to=params.get('to')?.replace(/^@/,''),legacy=params.get('channel');
 root.innerHTML=title('YOUR NETWORK / PRIVATE','MESSAGES')+`<form id="new-dm" class="dm-search">${field('handle','Message a player',to||'','text','required placeholder="Player handle" maxlength="24"')}<button class="button" type="submit">OPEN DM </button></form><div id="dm-content"></div>`;
 submit($('#new-dm',root),async b=>window.xbtNavigate('/social/messages?to='+encodeURIComponent(b.handle.replace(/^@/,''))));
 const content=$('#dm-content',root);
 if(!to&&!legacy){async function inbox(){const d=await api('/conversations');if(!content.isConnected)return;content.innerHTML=d.items.map(p=>`<article class="card dm-preview">${identity(p)}<p>${esc(p.content.slice(0,160))}</p><a class="text-link" href="/social/messages?to=${esc(p.handle)}" data-route>OPEN CONVERSATION </a></article>`).join('')||empty('NO CONVERSATIONS YET','Choose a player above, or use DM on a player card.');}await inbox();poll(inbox,6000);return;}
 const channel=to?'dm:'+to:legacy;let person=null;if(to)person=(await api('/players/'+encodeURIComponent(to))).profile;
 content.innerHTML=`<div class="dm-room">${person?`<div class="dm-person">${identity(person)}<span class="presence ${person.presence==='offline'?'offline':''}">${esc(person.presence)}</span></div>`:''}<div class="chat-log" role="log" aria-label="Direct messages" aria-live="polite"></div>${composer()}</div>`;
 const log=$('.chat-log',content);let previous='',first=true,busy=false;
 async function load(){if(busy)return;busy=true;try{const d=await api('/messages?channel='+encodeURIComponent(channel));if(!log.isConnected)return;const near=log.scrollTop+log.clientHeight>=log.scrollHeight-50,html=d.items.map(bubble).join('')||'<p class="chat-empty">Start the conversation.</p>';if(html!==previous){log.innerHTML=html;previous=html;if(near||first)log.scrollTop=log.scrollHeight;}first=false;}finally{busy=false;}}
 bindReports(content);submit($('form',content),async(b,f)=>{await api('/messages',{method:'POST',body:{channel,content:b.content}});f.reset();await load();log.scrollTop=log.scrollHeight;});await load();poll(load,4000);
}
