import {nameMarkup,flag} from './identity.js?v=20260930-terminal';
export const API=/^(www\.)?xbtesports\.nyc$/.test(location.hostname)||location.hostname.endsWith('.github.io')?'https://xbtesports-social.smithrock87.workers.dev/api/social':'/api/social';
export const ADMIN='https://xbtesports-calendar.smithrock87.workers.dev/social/admin';
export const state={user:null,token:'',cleanups:[]};try{state.token=sessionStorage.getItem('xbt-social-session')||'';}catch{}
export const $=(s,root=document)=>root.querySelector(s);
export const $$=(s,root=document)=>[...root.querySelectorAll(s)];
export const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
export const media=s=>s?.startsWith('/api/social/media/')?API+s.slice('/api/social'.length):'';
export const avatar=p=>p?.avatar?`<img class="avatar" src="${esc(media(p.avatar))}" alt="" loading="lazy">`:`<span class="avatar" aria-hidden="true">${esc((p?.display_name||p?.handle||'XBT').slice(0,2).toUpperCase())}</span>`;
export const identity=p=>`<a class="identity" href="/social/@${esc(p.handle)}" data-route>${avatar(p)}<span>${nameMarkup(p)}<small>@${esc(p.handle)}${p.country?' · '+flag(p.country):''}</small></span></a>`;
export const formatDate=(s,tz='America/New_York')=>{if(!s||!Number.isFinite(Date.parse(s)))return 'To be announced';const parts=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(s)),v=k=>parts.find(x=>x.type===k)?.value;return `${v('year')}-${v('month')}-${v('day')} ${v('hour')}:${v('minute')}`;};
export function title(kicker,text,action=''){return `<div class="page-title"><div><p class="eyebrow">${esc(kicker)}</p><h1>${esc(text)}</h1></div>${action}</div>`;}
export function empty(heading,text,action=''){return `<section class="empty"><h2>${esc(heading)}</h2><p>${esc(text)}</p>${action}</section>`;}
export const button=(text,action,cls='')=>`<button class="button ${cls}" data-action="${esc(action)}">${esc(text)}</button>`;
export function field(name,label,value='',type='text',extra=''){return `<label class="field"><span>${esc(label)}</span><input name="${esc(name)}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
export function select(name,label,options,value=''){return `<label class="field"><span>${esc(label)}</span><select name="${esc(name)}">${options.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`;}
export function area(name,label,value='',max=4000){return `<label class="field wide"><span>${esc(label)}</span><textarea name="${esc(name)}" maxlength="${max}">${esc(value)}</textarea></label>`;}
export const values=form=>Object.fromEntries(new FormData(form));
export async function api(path,options={}){const headers={...(state.token?{Authorization:'Bearer '+state.token}:{}),...options.headers};if(options.body&&!(options.body instanceof Blob)&&!(options.body instanceof ArrayBuffer)){headers['Content-Type']='application/json';options.body=JSON.stringify(options.body);}const response=await fetch(API+path,{...options,headers});let data;try{data=await response.json();}catch{throw Error('The service returned an unreadable response. Please retry.');}if(!response.ok)throw Error(data.error||'Please try again.');return data;}
export function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
export function modal(html){$('#dialog-content').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();}
export function close(){ $('#dialog').close();}
export function submit(form,fn){form.addEventListener('submit',async e=>{e.preventDefault();const b=$('button[type=submit]',form);if(b)b.disabled=true;$('.dialog-error',form)?.remove();try{await fn(values(form),form);}catch(error){form.insertAdjacentHTML('beforeend',`<p class="error dialog-error" role="alert">${esc(error.message)}</p>`);}finally{if(b)b.disabled=false;}});}
export function signIn(mode='login'){modal(`<h2>${mode==='signup'?'JOIN THE NETWORK':mode==='recover'?'RECOVER ACCOUNT':'WELCOME BACK'}</h2><form id="auth-form">${field('handle','@handle','','text','required minlength="3" maxlength="24" autocomplete="username"')}${mode==='recover'?field('recovery','Recovery key','','text','required autocomplete="off"'):''}${field('password',mode==='recover'?'New password':'Password','','password',`required minlength="12" maxlength="128" autocomplete="${mode==='login'?'current-password':'new-password'}"`)}<p class="muted">${mode==='signup'?'Use at least 12 characters. You’ll receive a recovery key; save it to recover your account.':'Your account keeps your profile, tournament entries and community activity together.'}</p><button class="button" type="submit">${mode==='signup'?'CREATE ACCOUNT':mode==='recover'?'RESET PASSWORD':'SIGN IN'} </button></form><div class="actions"><button class="button outline" id="auth-switch">${mode==='login'?'CREATE ACCOUNT':'BACK TO SIGN IN'}</button>${mode==='login'?'<button class="button outline" id="auth-recover">RECOVER ACCOUNT</button>':''}</div>`);
 $('#auth-switch').onclick=()=>signIn(mode==='login'?'signup':'login');if($('#auth-recover'))$('#auth-recover').onclick=()=>signIn('recover');submit($('#auth-form'),async b=>{const data=await api('/'+mode,{method:'POST',body:b});if(data.token){state.token=data.token;state.user=data.user;try{sessionStorage.setItem('xbt-social-session',data.token);}catch{}}if(data.recovery){modal(`<h2>SAVE YOUR RECOVERY KEY</h2><p>This key is shown once. Keep it somewhere private; it can reset your password.</p><code class="inline-code">${esc(data.recovery)}</code><div class="actions"><button id="copy-key" class="button outline">COPY KEY</button><button id="done-key" class="button">I HAVE SAVED IT</button></div>`);$('#copy-key').onclick=()=>copy(data.recovery);$('#done-key').onclick=()=>{close();window.dispatchEvent(new Event('xbt-session'));};}else{close();window.dispatchEvent(new Event('xbt-session'));}});}
export function signed(){if(state.user)return true;signIn();return false;}
export async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copied to clipboard.');}catch{modal(`<h2>COPY THIS</h2><textarea class="control" readonly>${esc(text)}</textarea>`);$('textarea',$('#dialog')).select();}}
export function bindActions(root,actions){root.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el||!root.contains(el))return;const fn=actions[el.dataset.action];if(!fn)return;e.preventDefault();try{await fn(el);}catch(error){toast(error.message);}});}
export function poll(fn,ms=10000){const t=setInterval(()=>{if(!document.hidden&&!$('#dialog').open)fn().catch(()=>{});},ms);state.cleanups.push(()=>clearInterval(t));}
export async function upload(file,kind='image'){if(!file)throw Error('Choose a file.');return api('/media?kind='+kind,{method:'POST',body:file,headers:{'Content-Type':'application/octet-stream'}});}
export function report(type,id){if(!signed())return;modal(`<h2>REPORT CONTENT</h2><form id="report-form">${select('reason','Reason',['Spam','Harassment','Inappropriate content','Impersonation','Cheating allegation','Scam','Other'])}${area('detail','Additional details','',2000)}<p class="muted">Only the moderation team can see this report.</p><button class="button" type="submit">SEND REPORT</button></form>`);submit($('#report-form'),async b=>{await api('/reports',{method:'POST',body:{...b,target_type:type,target_id:id}});close();toast('Report sent to the moderation team.');});}
