import {editExtras} from './profile-extras.js?v=20261003-notifications';
import {platformMarkup} from './platforms.js?v=20261003-notifications';
import {providerButtons} from './oauth.js?v=20261003-notifications';
import {esc,api,state,$,$$,modal,submit,close,toast,field,select,area,upload,avatar,media} from './core.js?v=20261003-notifications';
export const colors={red:'#ff3659',white:'#ffffff',blue:'#72b7ff',teal:'#70edcd',gold:'#ffda73'};
const fonts={standard:'Roboto, Arial, sans-serif',condensed:'"Barlow Condensed", sans-serif',tactical:'"Barlow", sans-serif',mono:'"Space Mono", monospace',bold:'Arial, sans-serif'};
const countries='US AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' ');
export const flag=code=>/^[A-Z]{2}$/.test(code?.toUpperCase()||'')?code.toUpperCase():'';
export const nameMarkup=p=>`<strong data-name-color="${esc(p.color||'white')}" data-name-font="${esc(p.font||'standard')}" data-font-url="${esc(p.font_url||'')}">${esc(p.display_name||p.handle)}</strong>`;
const loaded=new Map();
async function decorate(el){
 const key=[el.dataset.nameColor,el.dataset.nameFont,el.dataset.fontUrl].join('|');if(el.dataset.styled===key)return;el.dataset.styled=key;
 el.style.color=colors[el.dataset.nameColor]||(/^#[0-9a-f]{6}$/i.test(el.dataset.nameColor)?el.dataset.nameColor:'#fff');
 el.style.fontFamily=fonts[el.dataset.nameFont]||fonts.standard;
 const url=el.dataset.fontUrl;if(!url)return;
 try{if(!/^\/api\/social\/media\/[a-f0-9-]{36}$/.test(url))return;const u=new URL(media(url),location.origin);
  if(!loaded.has(url)){const family='XBTCustom'+loaded.size;loaded.set(url,new FontFace(family,`url(${JSON.stringify(u.href)})`).load().then(f=>{document.fonts.add(f);return family;}).catch(()=>null));}
  const family=await loaded.get(url);if(el.dataset.styled===key)el.style.fontFamily=family?`"${family}", Arial, sans-serif`:fonts.standard;
 }catch{el.style.fontFamily=fonts.standard;}
}
export function styleNames(root=document){if(root.matches?.('[data-name-color]'))decorate(root);root.querySelectorAll?.('[data-name-color]').forEach(decorate);}
new MutationObserver(records=>{for(const r of records)for(const n of r.addedNodes)if(n.nodeType===1)styleNames(n);}).observe(document.documentElement,{childList:true,subtree:true});
export function editIdentity(p,refresh){
 const display=new Intl.DisplayNames(['en'],{type:'region'}),hex=colors[p.color]||p.color||'#ffffff';
 modal(`<h2>MAKE IT YOURS</h2><p class="muted">Preview your name, then save. Your handle stays @${esc(p.handle)}.</p><div class="identity-preview">${avatar(p)}<div id="name-preview"></div></div><form id="identity-form"><fieldset><legend>1 · Your identity</legend><div id="provider-link"></div>${field('display_name','Display name',p.display_name,'text','required maxlength="40"')}${area('bio','About you',p.bio,500)}<label class="field"><span>Country</span><select name="country"><option value="US" ${p.country==='US'?'selected':''}>United States (US)</option><option value="" ${!p.country?'selected':''}>None</option>${countries.filter(c=>c!=='US').map(c=>`<option value="${c}" ${p.country===c?'selected':''}>${esc(display.of(c))} (${c})</option>`).join('')}</select></label>${select('presence','Show me as',['online','away','in tournament','offline'],p.preferred_presence||p.presence)}<p class="muted">Online status is shown while you are active. Offline hides you from the online count.</p></fieldset><fieldset><legend>2 · Name appearance</legend><div class="swatches">${Object.entries(colors).map(([n,c])=>`<button type="button" data-color="${c}" class="swatch ${n}" aria-label="${n}" title="${n}"></button>`).join('')}</div>${field('color','Hex color',hex,'text','required pattern="#[a-fA-F0-9]{6}" maxlength="7" placeholder="#FF3659"')}${select('font','Preset font',Object.keys(fonts),p.font)}${field('fontFile','Upload a custom font','','file','accept=".woff2,.woff,.ttf,.otf"')}<p class="muted">WOFF2, WOFF, TTF or OTF · up to 2 MB. Only upload fonts you have permission to use. If the font cannot load, a standard font is used.</p><label><input type="checkbox" name="removeFont"> Use preset instead of uploaded font</label></fieldset><fieldset><legend>3 · Pictures</legend>${field('avatarFile','Profile picture (static or animated)','','file','accept="image/png,image/jpeg,image/gif,image/webp"')}${field('bannerFile','Banner','','file','accept="image/png,image/jpeg,image/gif,image/webp"')}<p class="muted">PNG, JPEG, GIF or WebP · up to 4 MB each. Animated GIF and WebP stay animated.</p></fieldset><details><summary>Gaming details</summary>${field('games','Games',p.games,'text','placeholder="Call of Duty, Halo, Fortnite"')}<p class="muted">Separate each game with a comma. They appear as small labels on your profile.</p>${select('platform','Platform',['Not specified','Xbox Series X|S','Xbox One','PlayStation 5','PlayStation 4','Nintendo Switch 2','Nintendo Switch','PC','Steam Deck','Android','iOS','Other'],p.platform||'Not specified')}<div id="platform-preview"></div>${field('gamertag','Gamertag',p.gamertag)}</details><button class="button" type="submit">SAVE PROFILE</button><button class="button outline" type="submit" id="save-and-extras">SAVE & EDIT FAVORITES / WIDGETS</button></form>`);
 providerButtons($('#provider-link'),true);const form=$('#identity-form');let nextExtras=false;form.addEventListener('submit',e=>{nextExtras=e.submitter?.id==='save-and-extras';});const preview=()=>{const v=Object.fromEntries(new FormData(form));$('#platform-preview').innerHTML=platformMarkup(v.platform);$('#name-preview').innerHTML=nameMarkup(v)+` <span>${flag(v.country)}</span>`;};form.oninput=preview;form.onchange=preview;$$('[data-color]',form).forEach(b=>b.onclick=()=>{form.elements.color.value=b.dataset.color;preview();});preview();
 submit(form,async(b,f)=>{for(const n of ['avatar','banner']){const file=f.elements[n+'File'].files[0];b[n]=file?(await upload(file)).url:p[n];}delete b.avatarFile;delete b.bannerFile;const fontFile=f.elements.fontFile.files[0];b.font_url=b.removeFont?'':fontFile?(await upload(fontFile,'font')).url:p.font_url?.startsWith('/api/social/media/')?p.font_url:'';delete b.fontFile;delete b.removeFont;await api('/profile',{method:'PUT',body:b});state.user=(await api('/session')).user;close();window.dispatchEvent(new Event('xbt-profile'));toast('Profile saved.');await refresh();if(nextExtras)await editExtras(refresh);});
}
