import {platformMarkup} from './platforms.js?v=20260930-terminal2';
import {api,state,$,$$,esc,title,identity,empty,signed,modal,submit,close,toast,field,poll} from './core.js?v=20260930-terminal2';
export function events(root){root.innerHTML=`<iframe class="events-frame" title="XBT public event calendar" src="${['localhost','127.0.0.1'].includes(location.hostname)?'':'https://xbtesports-social.smithrock87.workers.dev'}/activetournament/?embed=1&v=20260930-terminal2"></iframe>`;}

function actions(p){if(p.id===state.user?.id)return '<a class="button outline" href="/social/profile" data-route>EDIT MY PROFILE</a>';return `<button class="button" data-friend="${esc(p.handle)}" data-action="${p.friendship==='accepted'?'remove':p.friendship==='pending'?p.friend_sender===state.user?.id?'cancel':'accept':'request'}">${p.friendship==='accepted'?'FRIENDS ':p.friendship==='pending'?p.friend_sender===state.user?.id?'CANCEL REQUEST':'ACCEPT FRIEND':'ADD FRIEND +'}</button>${p.friendship==='pending'&&p.friend_sender!==state.user?.id?`<button class="button outline" data-friend="${esc(p.handle)}" data-action="decline">DECLINE</button>`:''}<a class="button outline" href="/social/messages?to=${esc(p.handle)}" data-route>DM </a><button class="text-link" data-invite="${esc(p.handle)}">INVITE TO CREW</button>`;}
function card(p){return `<article class="card player-card">${identity(p)}<span class="presence ${p.presence==='offline'?'offline':''}">${esc(p.presence||'offline')}</span><p>${esc(p.bio||p.games||'Ready for the next game.')}</p>${platformMarkup(p.platform)}<div class="actions">${actions(p)}</div></article>`;}
export async function players(root){
 root.innerHTML=title('YOUR NETWORK','PLAYERS')+`<label class="field"><span>Find a player</span><input id="player-search" placeholder="Type any part of a name or handle…" maxlength="80" autocomplete="off"></label><div id="friend-requests"></div><div class="grid players-grid" id="player-results" aria-live="polite"></div>`;
 let seq=0,timer;async function load(){const n=++seq;const d=await api('/players?q='+encodeURIComponent($('#player-search',root).value));if(n!==seq||!root.isConnected)return;$('#player-results',root).innerHTML=d.items.map(card).join('')||empty('NO MATCHES','Try a different part of the player’s name.');if(state.user){const f=await api('/friends');if(n!==seq)return;const pending=f.items.filter(p=>p.friendship==='pending'&&p.friend_sender!==state.user.id);$('#friend-requests',root).innerHTML=pending.length?'<h2>FRIEND REQUESTS</h2>'+pending.map(card).join(''):'';}}
 $('#player-search',root).oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>load().catch(e=>toast(e.message)),180);};state.cleanups.push(()=>{clearTimeout(timer);seq++;});
 root.onclick=async e=>{const f=e.target.closest('[data-friend]'),i=e.target.closest('[data-invite]');if(!f&&!i)return;if(!signed())return;try{if(f){if(f.dataset.action==='remove'){modal('<h2>REMOVE FRIEND?</h2><p>You can send another request later.</p><button id="remove-friend" class="button">REMOVE FRIEND</button>');$('#remove-friend').onclick=async()=>{try{await api('/friends',{method:'POST',body:{handle:f.dataset.friend,action:'remove'}});close();await load();}catch(e){toast(e.message);}};return;}f.disabled=true;await api('/friends',{method:'POST',body:{handle:f.dataset.friend,action:f.dataset.action}});await load();}else{const d=await api('/my-crews');modal(`<h2>INVITE @${esc(i.dataset.invite)}</h2>${d.items.length?`<form id="invite-crew"><label class="field"><span>Choose your crew</span><select name="crew">${d.items.map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join('')}</select></label><button class="button" type="submit">SEND INVITE</button></form>`:'<p>Create a crew, or become a crew moderator, to invite players.</p><a id="create-crew-link" class="button" href="/social/crews" data-route>OPEN CREWS</a>'}`);if($('#create-crew-link'))$('#create-crew-link').onclick=close;if($('#invite-crew'))submit($('#invite-crew'),async b=>{await api('/groups/'+b.crew,{method:'POST',body:{action:'invite',handle:i.dataset.invite}});close();toast('Crew invitation sent.');});}}catch(error){toast(error.message);}finally{if(f)f.disabled=false;}};
 await load();poll(load,30000);
}
export function liveSearch(){const input=$('#search'),box=$('#search-results');let timer,seq=0;input.oninput=()=>{clearTimeout(timer);const q=input.value.trim(),n=++seq;if(!q){box.hidden=true;return;}timer=setTimeout(async()=>{try{const d=await api('/search?q='+encodeURIComponent(q));if(n!==seq)return;const links=[];for(const p of d.players)links.push(`<a href="/social/@${esc(p.handle)}" data-route>${identity(p).replace(/<a[^>]*>|<\/a>/g,'')}</a>`);for(const g of d.groups)links.push(`<a href="/social/crews/${esc(g.id)}" data-route>CREW · ${esc(g.name)}</a>`);for(const t of d.tournaments)links.push(`<a href="/social/tournaments/${esc(t.slug)}" data-route>EVENT · ${esc(t.title)}</a>`);box.innerHTML=links.slice(0,12).join('')||'<p>No character matches yet.</p>';box.hidden=false;}catch{box.innerHTML='<p>Search is unavailable. Please retry.</p>';box.hidden=false;}},180);};box.onclick=()=>{box.hidden=true;};input.onkeydown=e=>{if(e.key==='Escape'){seq++;box.hidden=true;}};document.addEventListener('click',e=>{if(!e.target.closest('#global-search')){seq++;box.hidden=true;}});$('#global-search').addEventListener('submit',()=>{seq++;box.hidden=true;});}
