import {api,$,$$,esc,media,modal,submit,close,toast,field,state,upload,poll} from './core.js?v=20261002-profile-remodel';

const credit=shot=>shot.source==='unsplash'?`<small>Photo by <a href="${esc(shot.profile)}?utm_source=xbtesports_social&utm_medium=referral" target="_blank" rel="noopener noreferrer">${esc(shot.name)}</a> on <a href="https://unsplash.com/?utm_source=xbtesports_social&utm_medium=referral" target="_blank" rel="noopener noreferrer">Unsplash</a></small>`:'';
const shotURL=shot=>shot.preview||(shot.source==='upload'?media(shot.url):shot.thumb||shot.url);
const defaults=()=>({games:[],shots:[],lastfm:'',clock:false,timezone:'America/New_York'});
export async function renderExtras(root,handle){
 try{
  const data=await api('/profile/extras/'+encodeURIComponent(handle));if(!root.isConnected)return;
  root.innerHTML=`${data.games.length?`<section class="profile-extra"><h2>Favorite games</h2><div class="favorite-games">${data.games.map(g=>`<figure>${g.cover?`<img src="${esc(g.cover)}" alt="" loading="lazy">`:''}<figcaption>${esc(g.name)}</figcaption></figure>`).join('')}</div><small>Game information from <a href="https://www.igdb.com" target="_blank" rel="noopener noreferrer">IGDB</a></small></section>`:''}${data.lastfm?'<section class="profile-extra"><h2>Listening activity</h2><div id="profile-music">Loading music…</div></section>':''}${data.clock?`<section class="profile-extra"><h2>My timezone</h2><div class="flip-clock" role="img" aria-label="Local time"><span></span><b aria-hidden="true">:</b><span></span><b aria-hidden="true">:</b><span></span></div><p class="muted clock-zone">${esc(data.timezone.replaceAll('_',' '))}</p></section>`:''}${data.shots.length?`<section class="profile-extra"><h2>Favorite shots</h2><div class="favorite-shots">${data.shots.map(s=>`<figure><img src="${esc(shotURL(s))}" alt="${esc(s.alt)}" loading="lazy">${credit(s)}</figure>`).join('')}</div></section>`:''}`;
  if(data.clock){const clock=$('.flip-clock',root);const tick=()=>{if(!clock.isConnected)return;const time=new Intl.DateTimeFormat('en-GB',{timeZone:data.timezone,hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date());clock.setAttribute('aria-label',time+' in '+data.timezone);time.split(':').forEach((v,i)=>{const cell=$$('span',clock)[i];if(cell.textContent===v)return;cell.textContent=v;if(!matchMedia('(prefers-reduced-motion: reduce)').matches)cell.animate([{transform:'rotateX(-35deg)',opacity:.6},{transform:'rotateX(0)',opacity:1}],{duration:260});});};tick();const timer=setInterval(tick,1000);state.cleanups.push(()=>clearInterval(timer));}
  if(data.lastfm){const music=$('#profile-music',root);const update=async()=>{try{const d=await api('/integrations/music/'+encodeURIComponent(handle));if(!music.isConnected)return;music.innerHTML=d.tracks.map(t=>`<p>${t.playing?'<small class="tag">Now playing</small> ':''}<a href="${esc(t.url||'https://www.last.fm')}" target="_blank" rel="noopener noreferrer">${esc(t.name)}</a><br><small>${esc(t.artist)}</small></p>`).join('')||'<p>No recent tracks shared.</p>';music.insertAdjacentHTML('beforeend',`<small>Listening activity from <a href="https://www.last.fm/user/${encodeURIComponent(data.lastfm)}" target="_blank" rel="noopener noreferrer">${esc(data.lastfm)} on Last.fm</a></small>`);}catch{if(music.isConnected)music.textContent='Listening activity is unavailable right now.';}};await update();poll(update,60000);}
 }catch{if(root.isConnected)root.innerHTML='<p class="muted">Profile extras are unavailable right now.</p>';}
}

export async function editExtras(refresh){
 let data,providers;try{[data,providers]=await Promise.all([api('/profile/extras'),api('/integrations')]);}catch(e){toast(e.message);return;}
 data={...defaults(),...data};
 modal(`<h2>Favorites & widgets</h2><p class="muted">Everything here is optional and visible on your public profile. Remove an item or switch off a widget to hide it.</p><form id="extras-form"><fieldset><legend>Favorite games</legend><p class="muted">Choose up to eight games. Your existing game labels stay separate.</p><div id="selected-games" class="selected-extras"></div>${providers.igdb?`${field('gameSearch','Find a game','','search','maxlength="60" placeholder="Search IGDB"')}<button class="button outline" type="button" id="search-games">FIND GAMES</button><div id="game-results" class="extra-results" aria-live="polite"></div>`:'<p class="muted">Game search will be available once IGDB is connected.</p>'}</fieldset><fieldset><legend>Listening activity</legend>${field('lastfm','Last.fm username',data.lastfm,'text','maxlength="32" placeholder="Your Last.fm username"')}<p class="muted">Shares recent tracks from that public Last.fm profile. This does not verify account ownership. Leave blank to hide.${providers.lastfm?'':' Music will appear once Last.fm is connected.'}</p></fieldset><fieldset><legend>Your timezone</legend><label><input name="clock" type="checkbox" ${data.clock?'checked':''}> Show a flip clock on my profile</label><label class="field"><span>Timezone</span><select name="timezone" id="clock-timezone"></select></label><p class="muted">Visitors see the current time in the timezone you select.</p></fieldset><fieldset><legend>Favorite shots</legend><p class="muted">Choose up to six images. Upload game screenshots or find photography on Unsplash.</p><div id="selected-shots" class="selected-extras"></div>${field('screenshot','Upload a screenshot','','file','accept="image/png,image/jpeg,image/gif,image/webp"')}<button type="button" class="button outline" id="add-screenshot">ADD SCREENSHOT</button><p class="muted">PNG, JPEG, GIF or WebP · up to 4 MB.</p>${providers.unsplash?`${field('photoSearch','Find an Unsplash image','','search','maxlength="60" placeholder="Neon, city, space…"')}<button class="button outline" type="button" id="search-photos">FIND IMAGES</button><div id="photo-results" class="extra-results" aria-live="polite"></div>`:'<p class="muted">Photo search will be available once Unsplash is connected.</p>'}</fieldset><button type="submit" class="button">SAVE FAVORITES & WIDGETS</button></form>`);
 const form=$('#extras-form');const zones=[...new Set([data.timezone,'UTC',...(Intl.supportedValuesOf?Intl.supportedValuesOf('timeZone'):['America/New_York','America/Chicago','America/Denver','America/Los_Angeles','Europe/London','Asia/Tokyo','Australia/Sydney'])])].sort();$('#clock-timezone',form).innerHTML=zones.map(z=>`<option value="${esc(z)}" ${z===data.timezone?'selected':''}>${esc(z.replaceAll('_',' '))}</option>`).join('');
 const draw=()=>{
  $('#selected-games',form).innerHTML=data.games.map((g,i)=>`<span class="game-tag">${esc(g.name)} <button type="button" data-remove-game="${i}" aria-label="Remove ${esc(g.name)}">×</button></span>`).join('')||'<p class="muted">No favorite games selected.</p>';
  $('#selected-shots',form).innerHTML=data.shots.map((s,i)=>`<figure><img src="${esc(shotURL(s))}" alt="${esc(s.alt||'Selected image')}">${credit(s)}<button type="button" class="text-link" data-remove-shot="${i}">Remove</button></figure>`).join('')||'<p class="muted">No favorite shots selected.</p>';
  $$('[data-remove-game]',form).forEach(b=>b.onclick=()=>{data.games.splice(Number(b.dataset.removeGame),1);draw();});$$('[data-remove-shot]',form).forEach(b=>b.onclick=()=>{data.shots.splice(Number(b.dataset.removeShot),1);draw();});
 };draw();
 const lookup=(button,input,result,type)=>{if(!$(button,form))return;$(button,form).onclick=async()=>{const b=$(button,form),container=$(result,form),q=form.elements[input].value.trim();if(q.length<2){container.textContent='Type at least two characters.';return;}b.disabled=true;container.textContent='Searching…';try{const d=await api('/integrations/'+type+'?q='+encodeURIComponent(q));if(!form.isConnected)return;container.innerHTML=d.items.map((item,i)=>type==='games'?`<button class="extra-choice" type="button" data-add="${i}">${item.cover?`<img src="${esc(item.cover)}" alt="">`:''}<span>${esc(item.name)}</span></button>`:`<figure><button class="extra-choice" type="button" data-add="${i}"><img src="${esc(item.thumb)}" alt="${esc(item.alt)}"><span>Add image</span></button>${credit({...item,source:'unsplash'})}</figure>`).join('')||'No matches. Try another search.';$$('[data-add]',container).forEach(btn=>btn.onclick=()=>{const item=d.items[Number(btn.dataset.add)],list=type==='games'?data.games:data.shots,limit=type==='games'?8:6;if(list.length>=limit){toast('You can choose up to '+limit+'.');return;}if(list.some(s=>s.id===item.id&&(type==='games'||s.source==='unsplash')))return;list.push(type==='games'?item:{...item,source:'unsplash'});draw();btn.disabled=true;});}catch(e){container.textContent=e.message;}finally{b.disabled=false;}};form.elements[input].addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$(button,form).click();}});};
 lookup('#search-games','gameSearch','#game-results','games');lookup('#search-photos','photoSearch','#photo-results','photos');
 $('#add-screenshot',form).onclick=async()=>{const button=$('#add-screenshot',form),file=form.elements.screenshot.files[0];if(!file){toast('Choose an image first.');return;}if(data.shots.length>=6){toast('You can choose up to six shots.');return;}button.disabled=true;try{const result=await upload(file);if(!form.isConnected)return;const preview=URL.createObjectURL(file);$('#dialog').addEventListener('close',()=>URL.revokeObjectURL(preview),{once:true});data.shots.push({preview,id:result.url.split('/').pop(),source:'upload',url:result.url,alt:'Favorite screenshot'});form.elements.screenshot.value='';draw();}catch(e){toast(e.message);}finally{button.disabled=false;}};
 submit(form,async b=>{await api('/profile/extras',{method:'PUT',body:{lastfm:b.lastfm,clock:form.elements.clock.checked,timezone:b.timezone,games:data.games.map(g=>g.id),shots:data.shots.map(s=>({id:s.id,source:s.source}))}});close();toast('Favorites and widgets saved.');await refresh();});
}
