import {finishSignIn,secondFactor} from './security.mjs';
import {fail,id,now,one,run,query,body,str,choice,hash,secret,rate,publicProfile} from './core.mjs';
import {pbkdf2Sync,scryptSync,timingSafeEqual} from 'node:crypto';
const reserved=new Set(['admin','administrator','xbtesports','support','tournaments','social','official','system','moderator','editor','host']);
export function handle(value){const s=str(value,'handle',24,true);if(!/^[A-Za-z0-9_]{3,24}$/.test(s)||reserved.has(s.toLowerCase()))throw fail('Use 3–24 letters, numbers or underscores. This handle may be reserved.');return s;}
export function password(value,salt,legacy=false){if(typeof value!=='string'||value.length<12||value.length>128)throw fail('Use a password of 12–128 characters.');if(legacy)return pbkdf2Sync(value,salt,210000,32,'sha512').toString('hex');return 'scrypt-v1$'+scryptSync(value,salt,32,{N:32768,r:8,p:3,maxmem:64*1024*1024}).toString('hex');}
export const equal=(a,b)=>a.length===b.length&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
export async function actor(request,db){const token=request.headers.get('Authorization')?.replace(/^Bearer /,'');if(!token)return null;const user=await one(db,'SELECT u.*,p.* FROM sessions s LEFT JOIN session_auth_versions v ON v.token_hash=s.token_hash JOIN users u ON u.id=s.user_id JOIN profiles p ON p.user_id=u.id WHERE s.token_hash=? AND s.expires_at>? AND COALESCE(v.auth_version,0)=u.auth_version',await hash(token),Date.now());if(!user)return null;if(['banned','suspended'].includes(user.status))throw fail('This account is suspended.',403);await run(db,'UPDATE users SET last_active=? WHERE id=? AND (last_active IS NULL OR last_active<?)',new Date().toISOString(),user.id,new Date(Date.now()-300000).toISOString());return publicProfile(user);}
export function requireUser(user,write=false){if(!user)throw fail('Sign in to continue.',401);if(write&&user.status==='muted')throw fail('This account is currently muted.',403);return user;}
export function staff(user,roles=['editor','administrator']){requireUser(user);if(!roles.includes(user.role))throw fail('This action requires an authorized editor.',403);}
export async function session(db,user){const row=await one(db,'SELECT * FROM users WHERE id=?',user.id);if(!row||['banned','suspended'].includes(row.status)||user.auth_version!==undefined&&row.auth_version!==user.auth_version)throw fail('Account security changed. Sign in again.',401);const token=secret(),tokenHash=await hash(token);const result=await db.batch([query(db,'INSERT INTO sessions(token_hash,user_id,expires_at) SELECT ?,id,? FROM users WHERE id=? AND auth_version=?',tokenHash,Date.now()+86400000,row.id,row.auth_version),query(db,'INSERT INTO session_auth_versions SELECT ?,? WHERE EXISTS(SELECT 1 FROM sessions WHERE token_hash=?)',tokenHash,row.auth_version,tokenHash)]);if(!result[0].meta.changes)throw fail('Account security changed. Sign in again.',401);return {token,user:publicProfile(await one(db,'SELECT u.*,p.* FROM users u JOIN profiles p ON p.user_id=u.id WHERE u.id=?',row.id))};}
export async function authRoute(request,env,path,user){const db=env.SOCIAL_DB;
 if(path==='/session'&&request.method==='GET')return {user};
 if(path==='/logout'&&request.method==='POST'){const t=request.headers.get('Authorization')?.replace(/^Bearer /,'');if(t)await run(db,'DELETE FROM sessions WHERE token_hash=?',await hash(t));if(user)await run(db,'DELETE FROM chat_presence WHERE user_id=?',user.id);return {ok:true};}
 if(['/signup','/login','/recover'].includes(path)&&request.method==='POST'){
  await rate(db,'auth-ip:'+await hash(request.headers.get('CF-Connecting-IP')||'local'),12,900);
  const b=await body(request),h=str(b.handle,'handle',24,true);await rate(db,'auth-h:'+h.toLowerCase(),10,900);
  if(path==='/signup'){handle(h);const salt=secret(),recovery=secret(),uid=id(),digest=password(b.password,salt);try{await db.batch([query(db,'INSERT INTO users(id,handle,password_hash,salt,recovery_hash,created_at) VALUES(?,?,?,?,?,?)',uid,h,digest,salt,await hash(recovery),now()),query(db,"INSERT INTO profiles(user_id,display_name,presence) VALUES(?,?,'online')",uid,h)]);}catch(e){if(String(e).includes('UNIQUE'))throw fail('That handle is already taken.',409);throw e;}return {...await session(db,{id:uid}),recovery};}
  const row=await one(db,'SELECT * FROM users WHERE handle=?',h);
  if(path==='/recover'){if(!row||!equal(await hash(str(b.recovery,'recovery key',128,true)),row.recovery_hash))throw fail('Handle or recovery key is incorrect.',401);if(['banned','suspended'].includes(row.status))throw fail('This account is suspended.',403);const salt=secret(),recovery=secret(),digest=password(b.password,salt);await secondFactor(env,row.id,b.code);const result=await db.batch([query(db,'UPDATE users SET password_hash=?,salt=?,recovery_hash=?,auth_version=auth_version+1 WHERE id=? AND auth_version=? AND recovery_hash=?',digest,salt,await hash(recovery),row.id,row.auth_version,row.recovery_hash),query(db,'DELETE FROM sessions WHERE user_id=?',row.id),query(db,'DELETE FROM auth_challenges WHERE user_id=?',row.id),query(db,'DELETE FROM account_email_tokens WHERE user_id=?',row.id),query(db,'UPDATE account_security SET pending_secret=NULL,pending_until=NULL WHERE user_id=?',row.id)]);if(!result[0].meta.changes)throw fail('Recovery key was already used. Try signing in.',401);return {recovery,ok:true};}
  const digest=password(b.password,row?.salt||'nonexistent-account',!!row?.password_hash&&!row.password_hash.startsWith('scrypt-v1$'));if(!row||!equal(digest,row.password_hash))throw fail('Handle or password is incorrect.',401);if(['banned','suspended'].includes(row.status))throw fail('This account is suspended.',403);return finishSignIn(env,row);
 }
 if(path==='/profile'&&request.method==='PUT'){requireUser(user,true);const b=await body(request);b.country=str(b.country,'country',2).toUpperCase();if(b.country&&!/^[A-Z]{2}$/.test(b.country))throw fail('Choose a country flag or none.');const fontURL=str(b.font_url,'font URL',1000);if(fontURL&&(!/^\/api\/social\/media\/[a-f0-9-]{36}$/.test(fontURL)||!await one(db,"SELECT 1 FROM media WHERE id=? AND user_id=? AND kind='font'",fontURL.split('/').pop(),user.id)))throw fail('Upload your own font first.');const values=[str(b.display_name,'display name',40,true),str(b.bio,'bio',500),str(b.country,'country',2),str(b.avatar,'avatar',200),str(b.banner,'banner',200),(/^#[0-9a-f]{6}$/i.test(b.color)?b.color:choice(b.color,['teal','white','blue','red','gold'],'color')),choice(b.font,['condensed','tactical','mono','bold','standard'],'font'),str(b.games,'games',200),str(b.platform,'platform',60),str(b.gamertag,'gamertag',80),str(b.region,'region',80),str(b.preferred_role,'preferred role',80),choice(b.presence,['online','away','in tournament','offline'],'presence')];
  for(const media of [b.avatar,b.banner])if(media){if(!/^\/api\/social\/media\/[a-f0-9-]{36}$/.test(media)||!await one(db,"SELECT 1 FROM media WHERE id=? AND user_id=? AND kind='image'",media.split('/').pop(),user.id))throw fail('Upload your own profile image first.');}
  await run(db,'UPDATE profiles SET display_name=?,bio=?,country=?,avatar=?,banner=?,color=?,font=?,games=?,platform=?,gamertag=?,region=?,preferred_role=?,presence=?,font_url=? WHERE user_id=?',...values,fontURL,user.id);return {ok:true};}
 return undefined;
}
