import {fail,num,choice} from './core.mjs';
export const FORMATS=['Single Elimination','Double Elimination','Round Robin','Swiss','Free For All'];
export function settings(input={}){return {roundRobinRounds:Math.floor(num(input.roundRobinRounds??0,'round robin rounds',0,128)),tiebreak:choice(input.tiebreak||'buchholz',['buchholz','wins','seed'],'tiebreak'),pairing:choice(input.pairing||'score',['score','seed'],'pairing rule'),preventRepeats:input.preventRepeats!==false&&input.preventRepeats!=='allow repeats',advancement:typeof input.advancement==='string'?input.advancement.split(',').filter(x=>x.trim()).map(x=>Math.floor(num(x,'advancement count',1,128))):Array.isArray(input.advancement)?input.advancement.map(x=>Math.floor(num(x,'advancement count',1,128))):[],rounds:Math.floor(num(input.rounds??3,'rounds',1,16)),groups:Math.floor(num(input.groups??1,'groups',1,16)),lobbySize:Math.floor(num(input.lobbySize??12,'lobby size',2,64)),advance:Math.floor(num(input.advance??4,'advancement count',1,63)),winPoints:num(input.winPoints??3,'win points',0,100),drawPoints:num(input.drawPoints??1,'draw points',0,100),killPoints:num(input.killPoints??1,'elimination points',0,100),placementPoints:num(input.placementPoints??10,'placement points',0,100),scorePoints:num(input.scorePoints??1,'score multiplier',0,100),advanceBy:choice(input.advanceBy??'score',['score','placement','eliminations'],'advancement rule')};}
function match(id,round,sources,section='Winners'){return {id,round,sources,section,players:[],status:'Waiting',scores:[],winner:null,loser:null,map:'',mode:'',notes:'',stream:'',start:'',proof:'',result:null};}
function seeds(n){let s=[1,2];for(let count=4;count<=n;count*=2)s=s.flatMap(x=>[x,count+1-x]);return s;}
function elimination(players,double,slots=players.map(p=>p.id)){let n=2;while(n<slots.length)n*=2;const matches=[],k=Math.log2(n),seedOrder=seeds(n);for(let r=1;r<=k;r++)for(let j=0;j<n/(2**r);j++){const sources=r===1?[{player:slots[seedOrder[j*2]-1]||null},{player:slots[seedOrder[j*2+1]-1]||null}]:[{win:`W${r-1}-${j*2}`},{win:`W${r-1}-${j*2+1}`}];matches.push(match(`W${r}-${j}`,r,sources));}
 if(double&&n>2){for(let r=1;r<=2*(k-1);r++){const count=n/(2**(Math.floor((r+1)/2)+1));for(let j=0;j<count;j++){let sources;if(r===1)sources=[{lose:`W1-${j*2}`},{lose:`W1-${j*2+1}`}];else if(r%2===0)sources=[{win:`L${r-1}-${j}`},{lose:`W${r/2+1}-${count===1?j:count-1-j}`}];else sources=[{win:`L${r-1}-${j*2}`},{win:`L${r-1}-${j*2+1}`}];matches.push(match(`L${r}-${j}`,r,sources,'Losers'));}}}
 if(double){matches.push(match('GF',k+1,[{win:`W${k}-0`},n===2?{lose:'W1-0'}:{win:`L${2*(k-1)}-0`}],'Final'));}
 return matches;}
function robin(players,config){const result=[];for(let g=0;g<config.groups;g++){const pool=players.filter((_,i)=>i%config.groups===g).map(p=>p.id);if(pool.length<2)continue;if(pool.length%2)pool.push(null);const rounds=Math.min(config.roundRobinRounds||pool.length-1,pool.length-1);for(let r=1;r<=rounds;r++){for(let i=0;i<pool.length/2;i++)result.push(match(`G${g+1}-${r}-${i}`,r,[{player:pool[i]},{player:pool[pool.length-1-i]}],`Pool ${g+1}`));pool.splice(1,0,pool.pop());}}return result;}
export function createBracket(players,format,config={},slots=null){choice(format,FORMATS,'format');if(players.length<2||players.length>128)throw fail('A bracket needs 2–128 approved players.');if(new Set(players.map(p=>p.id)).size!==players.length)throw fail('Each player must have a unique seed.');if(slots&&(slots.length>256||new Set(slots.filter(Boolean)).size!==players.length||slots.filter(Boolean).length!==players.length||players.some(p=>!slots.includes(p.id))))throw fail('Invalid player and bye positions.');const s={format,slots:slots||players.map(p=>p.id),config:settings(config),players,matches:[],locked:false,paused:false,completed:false,champion:null};
 if(format.includes('Elimination'))s.matches=elimination(players,format==='Double Elimination',s.slots);
 else if(format==='Round Robin'){if(s.config.groups>Math.floor(players.length/2))throw fail('Each pool needs at least two players.');s.matches=robin(players,s.config);}
 else if(format==='Swiss')swiss(s);
 else ffa(s,players.map(p=>p.id),1);
 propagate(s);return s;}
function resolve(source,s){if('player' in source)return {ready:true,id:source.player};const m=s.matches.find(m=>m.id===(source.win||source.lose));return {ready:!!m&&m.status==='Completed',id:source.win?m?.winner:m?.loser};}
export function propagate(s){for(const m of s.matches){if(m.section==='FFA')continue;const resolved=m.sources.map(x=>resolve(x,s));if(!resolved.every(x=>x.ready)){m.status='Waiting';m.players=resolved.map(x=>x.id||null);continue;}m.players=resolved.map(x=>x.id||null);if(m.status==='Completed')continue;const dq=m.players.filter(id=>id&&s.disqualified?.includes(id));if(dq.length){m.winner=m.players.find(id=>id&&!s.disqualified.includes(id))||null;m.loser=dq.length===1?dq[0]:null;m.status='Completed';m.forfeit=true;m.scores=m.players.map(id=>id===m.winner?1:0);continue;}const real=m.players.filter(Boolean);if(real.length<2){m.status='Completed';m.winner=real[0]||null;m.loser=null;m.bye=true;}else{m.status='Ready';m.bye=false;}}
 if(s.format==='Double Elimination'){const gf=s.matches.find(m=>m.id==='GF');if(gf?.status==='Completed'&&gf.winner===gf.players[1]&&!s.matches.some(m=>m.id==='RESET')){s.matches.push(match('RESET',gf.round+1,gf.players.map(player=>({player})),'Final'));propagate(s);return;}}
 s.completed=s.matches.length>0&&s.matches.every(m=>m.status==='Completed')&&(s.format!=='Swiss'||Math.max(...s.matches.map(m=>m.round))>=s.config.rounds)&&(s.format!=='Free For All'||Math.max(...s.matches.map(m=>m.round))>=s.config.rounds||s.matches.at(-1).players.length<=1);
 if(s.completed){const final=s.matches.at(-1);s.champion=s.format.includes('Elimination')?final.winner:s.format==='Free For All'&&s.matches.filter(m=>m.round===final.round).length===1?final.winner:standings(s)[0]?.id||null;}}
export function standings(s){const all=s.players.map(p=>({...p,wins:0,losses:0,draws:0,points:0,played:0,eliminations:0,placements:[],opponents:[],buchholz:0})),byId=Object.fromEntries(all.map(p=>[p.id,p]));for(const m of s.matches){if(m.status!=='Completed')continue;if(m.section==='FFA'){for(const entry of m.result||[]){const p=byId[entry.id];if(!p)continue;p.played++;p.placements.push(entry.placement);p.eliminations+=entry.eliminations;p.points+=entry.total;if(entry.placement===1)p.wins++;else p.losses++;}continue;}if(m.bye){if(s.format==='Swiss'&&byId[m.winner])byId[m.winner].points+=s.config.winPoints;continue;}for(const pid of m.players){const p=byId[pid];if(!p)continue;p.played++;p.opponents.push(...m.players.filter(x=>x&&x!==pid));if(m.winner===pid){p.wins++;p.points+=s.config.winPoints;}else if(m.winner){p.losses++;}else{p.draws++;p.points+=s.config.drawPoints;}}}
 for(const p of all){p.buchholz=p.opponents.reduce((a,id)=>a+(byId[id]?.points||0),0);p.averagePlacement=p.placements.length?p.placements.reduce((a,b)=>a+b,0)/p.placements.length:null;}
 return all.sort((a,b)=>b.points-a.points||(s.config.tiebreak==='buchholz'?b.buchholz-a.buchholz:s.config.tiebreak==='wins'?b.wins-a.wins:0)||a.seed-b.seed);}
function swiss(s){
 const round=s.matches.length?Math.max(...s.matches.map(m=>m.round))+1:1;
 const ranked=(s.matches.length?standings(s):s.players.map(p=>({...p,opponents:[]}))).filter(p=>!s.disqualified?.includes(p.id));if(s.config.pairing==='seed')ranked.sort((a,b)=>a.seed-b.seed);if(ranked.length<2){s.completed=true;s.champion=ranked[0]?.id||null;return;}
 let budget=12000;
 function pair(list){if(!list.length)return [];if(--budget<0)return null;const a=list[0];for(let i=1;i<list.length;i++){const b=list[i];if(s.config.preventRepeats&&a.opponents.includes(b.id))continue;const rest=pair(list.filter((_,j)=>j!==0&&j!==i));if(rest)return [[a,b],...rest];}return null;}
 let bye=null,pairs=null,available=[...ranked];
 if(available.length%2){const candidates=[...available].reverse().sort((a,b)=>Number(s.matches.some(m=>m.bye&&m.winner===a.id))-Number(s.matches.some(m=>m.bye&&m.winner===b.id)));for(const candidate of candidates){const trial=pair(available.filter(p=>p.id!==candidate.id));if(trial){bye=candidate;pairs=trial;break;}}if(!pairs){bye=candidates[0];available=available.filter(p=>p.id!==bye.id);}}
 else pairs=pair(available);
 if(!pairs){pairs=[];while(available.length){const a=available.shift();let i=available.findIndex(p=>!a.opponents.includes(p.id));if(i<0)i=0;pairs.push([a,available.splice(i,1)[0]]);}}
 if(bye)s.matches.push(match(`S${round}-bye`,round,[{player:bye.id},{player:null}],'Swiss'));
 pairs.forEach(([a,b],i)=>s.matches.push(match(`S${round}-${i}`,round,[{player:a.id},{player:b.id}],'Swiss')));
}
function ffa(s,players,round){for(let i=0;i<players.length;i+=s.config.lobbySize){const ids=players.slice(i,i+s.config.lobbySize);s.matches.push({...match(`FFA${round}-${i/s.config.lobbySize}`,round,ids.map(player=>({player})),'FFA'),players:ids,status:ids.length===1?'Completed':'Ready',winner:ids.length===1?ids[0]:null,bye:ids.length===1,result:ids.length===1?[{id:ids[0],placement:1,eliminations:0,score:0,total:0}]:null});}}
export function nextRound(s){if(!s.matches.every(m=>m.status==='Completed'))throw fail('Finish the current round first.');const round=Math.max(...s.matches.map(m=>m.round));if(round>=s.config.rounds)throw fail('All configured rounds are complete.');if(s.format==='Swiss')swiss(s);else if(s.format==='Free For All'){const adv=s.matches.filter(m=>m.round===round).flatMap(m=>[...(m.result||[])].sort((a,b)=>s.config.advanceBy==='placement'?a.placement-b.placement:s.config.advanceBy==='eliminations'?b.eliminations-a.eliminations||a.placement-b.placement:b.total-a.total||a.placement-b.placement).slice(0,s.config.advancement[round-1]||s.config.advance).map(p=>p.id)).filter(id=>!s.disqualified?.includes(id));if(adv.length<2){s.completed=true;s.champion=adv[0]||null;return s;}ffa(s,adv,round+1);}else throw fail('This format already has its rounds.');propagate(s);return s;}
function invalidate(s,id){const descendants=s.matches.filter(m=>m.sources.some(x=>x.win===id||x.lose===id));for(const m of descendants){invalidate(s,m.id);m.status='Waiting';m.result=null;m.winner=null;m.loser=null;m.scores=[];}if(id==='GF')s.matches=s.matches.filter(m=>m.id!=='RESET');}
export function result(s,matchId,input){if(s.paused)throw fail('Resume the bracket before entering results.');const m=s.matches.find(x=>x.id===matchId);if(!m||m.status==='Waiting'||m.bye)throw fail('This match is not ready.');if(m.status==='Completed'){if(['Swiss','Free For All'].includes(s.format)){s.matches=s.matches.filter(x=>x.round<=m.round);}invalidate(s,m.id);}
 if(s.format==='Free For All'){if(!Array.isArray(input.results)||input.results.length!==m.players.length)throw fail('Enter a result for every lobby player.');if(new Set(input.results.map(r=>r.id)).size!==m.players.length||input.results.some(r=>!m.players.includes(r.id)))throw fail('Invalid lobby players.');m.result=input.results.map(r=>({id:r.id,placement:Math.floor(num(r.placement,'placement',1,m.players.length)),eliminations:num(r.eliminations,'eliminations',0,10000),score:num(r.score||0,'score',0,100000)}));if(new Set(m.result.map(r=>r.placement)).size!==m.result.length)throw fail('Placements must be unique.');for(const r of m.result)r.total=r.eliminations*s.config.killPoints+Math.max(0,s.config.placementPoints-r.placement+1)+r.score*s.config.scorePoints;m.winner=[...m.result].sort((a,b)=>a.placement-b.placement)[0].id;
 }else {m.scores=[num(input.a,'score',0,100000),num(input.b,'score',0,100000)];if(m.scores[0]===m.scores[1]&&s.format.includes('Elimination'))throw fail('Elimination matches cannot end in a draw.');m.winner=m.scores[0]===m.scores[1]?null:m.players[m.scores[0]>m.scores[1]?0:1];m.loser=m.winner?m.players.find(x=>x!==m.winner):null;}
 m.status='Completed';s.completed=false;s.champion=null;propagate(s);return s;}
