import {fail,id,now,one,rows,run,query,body,str,choice,url,page,notify} from './core.mjs';
import {telemetry} from './telemetry.mjs';
import {requireUser,staff,handle} from './auth.mjs';
const profileFields='u.id,u.handle,p.display_name,p.bio,p.country,p.avatar,p.banner,p.color,p.font,p.font_url,p.games,p.platform,p.gamertag,p.region,p.preferred_role,p.presence';
const postFields=`p.*,u.handle,pr.display_name,pr.avatar,pr.color,pr.font,pr.font_url,pr.country,(SELECT count(*) FROM likes WHERE post_id=p.id) likes,(SELECT count(*) FROM posts WHERE parent_id=p.id AND removed=0) replies`;
const postJoin='FROM posts p JOIN users u ON u.id=p.user_id JOIN profiles pr ON pr.user_id=u.id';
const visibleGroup=`(p.group_id IS NULL OR EXISTS(SELECT 1 FROM groups g WHERE g.id=p.group_id AND (g.privacy='Public' OR EXISTS(SELECT 1 FROM group_members gm WHERE gm.group_id=g.id AND gm.user_id=? AND gm.status='accepted'))))`;
async function group(db,gid,user,write=false){const g=await one(db,'SELECT * FROM groups WHERE id=?',gid);if(!g)throw fail('Group not found.',404);const m=user?await one(db,'SELECT * FROM group_members WHERE group_id=? AND user_id=?',gid,user.id):null;if((write||g.privacy!=='Public')&&m?.status!=='accepted')throw fail('Join this group to continue.',403);return {g,m};}
async function accessPost(db,pid,user){const p=await one(db,`SELECT p.* FROM posts p WHERE p.id=? AND p.removed=0 AND ${visibleGroup}`,pid,user?.id||'');if(!p)throw fail('Post not found.',404);return p;}
async function blocked(db,a,b){return !!await one(db,'SELECT 1 FROM blocks WHERE (user_id=? AND target_id=?) OR(user_id=? AND target_id=?)',a,b,b,a);}
export async function communityRoute(request,env,path,user){const db=env.SOCIAL_DB,method=request.method,u=new URL(request.url),parts=path.split('/').filter(Boolean);
 if(path==='/players'&&method==='GET'){const q='%'+str(u.searchParams.get('q'),'search',80)+'%',game='%'+str(u.searchParams.get('game'),'game',80)+'%',country=str(u.searchParams.get('country'),'country',2),platform='%'+str(u.searchParams.get('platform'),'platform',60)+'%';return {items:await rows(db,`SELECT ${profileFields} FROM users u JOIN profiles p ON p.user_id=u.id WHERE u.status NOT IN ('banned','suspended') AND (u.handle LIKE ? OR p.display_name LIKE ?) AND p.games LIKE ? AND p.platform LIKE ? AND (?='' OR p.country=?) ORDER BY u.last_active DESC,u.created_at DESC LIMIT 30 OFFSET ?`,q,q,game,platform,country,country,page(u))};}
 if(parts[0]==='players'&&parts[1]&&method==='GET'){const p=await one(db,`SELECT ${profileFields} FROM users u JOIN profiles p ON p.user_id=u.id WHERE u.handle=? AND u.status NOT IN ('banned','suspended')`,parts[1].replace(/^@/,''));if(!p)throw fail('Player not found.',404);const record=await telemetry(db,p.id);return {profile:{...p,presence:p.presence!=='offline'&&await one(db,'SELECT 1 FROM chat_presence WHERE user_id=? AND seen_at>?',p.id,Date.now()-90000)?p.presence:'offline',preferred_presence:p.presence},...record,followers:(await one(db,'SELECT count(*) n FROM follows WHERE following_id=?',p.id)).n,following:(await one(db,'SELECT count(*) n FROM follows WHERE follower_id=?',p.id)).n,isFollowing:user?!!await one(db,'SELECT 1 FROM follows WHERE follower_id=? AND following_id=?',user.id,p.id):false};}
 if(parts[0]==='players'&&parts[2]==='follow'&&method==='POST'){requireUser(user,true);const p=await one(db,'SELECT id FROM users WHERE handle=?',parts[1]);if(!p||p.id===user.id)throw fail('Choose another player.');if(await blocked(db,user.id,p.id))throw fail('This player is unavailable.',403);const exists=await one(db,'SELECT 1 FROM follows WHERE follower_id=? AND following_id=?',user.id,p.id);if(exists)await run(db,'DELETE FROM follows WHERE follower_id=? AND following_id=?',user.id,p.id);else{await run(db,'INSERT OR IGNORE INTO follows VALUES(?,?)',user.id,p.id);await notify(db,p.id,`@${user.handle} followed you`,`/social/@${user.handle}`);}return {following:!exists};}
 if(path==='/posts'&&method==='GET'){const kind=choice(u.searchParams.get('kind')||'post',['post','thread','clip','comment'],'post type'),parent=u.searchParams.get('parent')||'',gid=u.searchParams.get('group')||'',author=u.searchParams.get('author')||'',category=u.searchParams.get('category')||'',q='%'+str(u.searchParams.get('q'),'search',80)+'%';return {items:await rows(db,`SELECT ${postFields} ${postJoin} WHERE p.kind=? AND p.removed=0 AND (?='' OR p.parent_id=?) AND (?='' OR p.group_id=?) AND (?='' OR u.handle=?) AND (?='' OR p.category=?) AND (p.content LIKE ? OR p.title LIKE ?) AND ${visibleGroup} AND NOT EXISTS(SELECT 1 FROM blocks b WHERE(b.user_id=? AND b.target_id=p.user_id) OR(b.user_id=p.user_id AND b.target_id=?)) AND NOT EXISTS(SELECT 1 FROM mutes WHERE user_id=? AND target_id=p.user_id) ${u.searchParams.get('following')==='1'?'AND EXISTS(SELECT 1 FROM follows WHERE follower_id=? AND following_id=p.user_id)':''} ORDER BY p.pinned DESC,p.created_at DESC LIMIT 30 OFFSET ?`,kind,parent,parent,gid,gid,author,author,category,category,q,q,user?.id||'',user?.id||'',user?.id||'',user?.id||'',...(u.searchParams.get('following')==='1'?[user?.id||'']:[]),page(u))};}
 if(path==='/posts'&&method==='POST'){requireUser(user,true);const b=await body(request),kind=choice(b.kind||'post',['post','thread','clip','comment'],'post type'),content=str(b.content,'post',4000,true),pid=id();if(b.group_id)await group(db,b.group_id,user,true);let parent;if(kind==='comment'){parent=await accessPost(db,str(b.parent_id,'parent',36,true),user);if(parent.locked)throw fail('This thread is locked.');if(await blocked(db,user.id,parent.user_id))throw fail('This conversation is unavailable.',403);b.group_id=parent.group_id;}
  if(kind==='thread'&&!await one(db,'SELECT 1 FROM forum_categories WHERE name=?',b.category))throw fail('Choose a forum category.');if(b.tournament_id&&!await one(db,"SELECT 1 FROM tournaments WHERE id=? AND status<>'Draft'",str(b.tournament_id,'tournament',36)))throw fail('Choose a published tournament ID.');let media=str(b.media,'media',200);if(media){if(!/^\/api\/social\/media\/[a-f0-9-]{36}$/.test(media))throw fail('Upload media first.');const m=await one(db,'SELECT user_id,kind FROM media WHERE id=?',media.split('/').pop());if(!m||m.user_id!==user.id||(kind==='clip'?m.kind!=='clip':m.kind!=='image'))throw fail('Invalid media.');}if(kind==='clip'&&!media)throw fail('Upload a clip first.');await run(db,'INSERT INTO posts(id,user_id,kind,parent_id,group_id,category,title,content,media,tournament_id,created_at,game,tags) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',pid,user.id,kind,parent?.id||null,b.group_id||null,str(b.category,'category',80),str(b.title,'title',140,kind==='thread'||kind==='clip'),content,media,b.tournament_id||null,now(),str(b.game,'game',120),str(b.tags,'tags',200));if(parent&&parent.user_id!==user.id)await notify(db,parent.user_id,`@${user.handle} replied to you`,`/social/post/${parent.id}`);for(const mention of [...content.matchAll(/@([A-Za-z0-9_]{3,24})/g)].slice(0,10)){const p=await one(db,'SELECT id FROM users WHERE handle=?',mention[1]);if(p&&p.id!==user.id&&!await blocked(db,p.id,user.id))await notify(db,p.id,`@${user.handle} mentioned you`,`/social/post/${pid}`);}return {id:pid};}
 if(parts[0]==='posts'&&parts[1]){const p=await accessPost(db,parts[1],user);if(method==='GET')return {post:await one(db,`SELECT ${postFields} ${postJoin} WHERE p.id=?`,p.id)};requireUser(user,true);if(method==='DELETE'){if(p.user_id!==user.id)staff(user,['moderator','editor','administrator']);await run(db,'UPDATE posts SET removed=1 WHERE id IN (WITH RECURSIVE children(id) AS (SELECT id FROM posts WHERE id=? UNION ALL SELECT p.id FROM posts p JOIN children c ON p.parent_id=c.id) SELECT id FROM children) AND ? IS NOT NULL',p.id,p.id);return {ok:true};}if(parts[2]==='like'&&method==='POST'){const exists=await one(db,'SELECT 1 FROM likes WHERE user_id=? AND post_id=?',user.id,p.id);if(exists)await run(db,'DELETE FROM likes WHERE user_id=? AND post_id=?',user.id,p.id);else await run(db,'INSERT OR IGNORE INTO likes VALUES(?,?)',user.id,p.id);return {liked:!exists};}}
 if(path==='/categories'&&method==='GET')return {items:await rows(db,'SELECT * FROM forum_categories ORDER BY name')};
 if(path==='/groups'&&method==='GET')return {items:await rows(db,"SELECT g.*,(SELECT count(*) FROM group_members WHERE group_id=g.id AND status='accepted') members FROM groups g WHERE name LIKE ? ORDER BY created_at DESC LIMIT 30 OFFSET ?",'%'+str(u.searchParams.get('q'),'search',80)+'%',page(u))};
 if(path==='/groups'&&method==='POST'){requireUser(user,true);const b=await body(request),gid=id(),avatar=str(b.avatar,'avatar',200);if(avatar&&(!/^\/api\/social\/media\/[a-f0-9-]{36}$/.test(avatar)||!await one(db,"SELECT 1 FROM media WHERE id=? AND user_id=? AND kind='image'",avatar.split('/').pop(),user.id)))throw fail('Upload your own crew picture first.');await db.batch([query(db,'INSERT INTO groups(id,handle,name,description,owner_id,privacy,games,created_at,avatar) VALUES(?,?,?,?,?,?,?,?,?)',gid,handle(b.handle),str(b.name,'group name',80,true),str(b.description,'description',1000),user.id,choice(b.privacy,['Public','Request to Join','Invite Only'],'privacy'),str(b.games,'games',200),now(),avatar),query(db,"INSERT INTO group_members VALUES(?,?,'owner','accepted')",gid,user.id)]);return {id:gid};}
 if(parts[0]==='groups'&&parts[1]){const g=await one(db,'SELECT * FROM groups WHERE id=?',parts[1]);if(!g)throw fail('Group not found.',404);const membership=user?await one(db,'SELECT * FROM group_members WHERE group_id=? AND user_id=?',g.id,user.id):null;
  if(method==='GET')return {group:g,membership,members:g.privacy==='Public'||membership?.status==='accepted'?await rows(db,`SELECT ${profileFields},gm.role,gm.status FROM group_members gm JOIN users u ON u.id=gm.user_id JOIN profiles p ON p.user_id=u.id WHERE gm.group_id=? AND (gm.status='accepted' OR ?=?) LIMIT 128`,g.id,user?.id||'',g.owner_id):[]};
  requireUser(user,true);if(method==='PUT'){if(membership?.status!=='accepted'||!['owner','moderator'].includes(membership.role))throw fail('Group manager required.',403);const b=await body(request),avatar=str(b.avatar,'avatar',200);if(avatar&&(!/^\/api\/social\/media\/[a-f0-9-]{36}$/.test(avatar)||!await one(db,"SELECT 1 FROM media WHERE id=? AND user_id=? AND kind='image'",avatar.split('/').pop(),user.id)))throw fail('Upload your own crew picture first.');await run(db,'UPDATE groups SET avatar=? WHERE id=?',avatar,g.id);return {ok:true};}if(method==='POST'){const b=await body(request);if(b.action==='join'){if(g.privacy==='Invite Only'&&membership?.status!=='invited')throw fail('This group requires an invitation.');await run(db,"INSERT INTO group_members VALUES(?,?,'member',?) ON CONFLICT(group_id,user_id) DO UPDATE SET status=excluded.status",g.id,user.id,g.privacy==='Public'||membership?.status==='invited'?'accepted':'pending');return {ok:true};}if(b.action==='leave'){if(g.owner_id===user.id)throw fail('The owner cannot leave their group.');await run(db,'DELETE FROM group_members WHERE group_id=? AND user_id=?',g.id,user.id);return {ok:true};}if(membership?.status!=='accepted'||!['owner','moderator'].includes(membership?.role))throw fail('Group manager required.',403);const target=await one(db,'SELECT id FROM users WHERE handle=?',str(b.handle,'handle',24,true));if(!target||target.id===g.owner_id)throw fail('Choose another member.');if(b.action==='remove')await run(db,'DELETE FROM group_members WHERE group_id=? AND user_id=?',g.id,target.id);else if(b.action==='invite'){await run(db,"INSERT OR IGNORE INTO group_members VALUES(?,?,'member','invited')",g.id,target.id);await notify(db,target.id,`Invitation to ${g.name}`,`/social/groups/${g.id}`);}else if(b.action==='approve')await run(db,"UPDATE group_members SET status='accepted' WHERE group_id=? AND user_id=?",g.id,target.id);else if(b.action==='moderator'&&g.owner_id===user.id)await run(db,"UPDATE group_members SET role='moderator' WHERE group_id=? AND user_id=? AND status='accepted'",g.id,target.id);else throw fail('Unknown group action.');return {ok:true};}}
 if(path==='/notifications'){requireUser(user);if(method==='GET')return {items:await rows(db,'SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 30 OFFSET ?',user.id,page(u))};if(method==='POST'){await run(db,'UPDATE notifications SET is_read=1 WHERE user_id=?',user.id);return {ok:true};}}
 if(path==='/messages'){requireUser(user,method==='POST');const b=method==='POST'?await body(request):Object.fromEntries(u.searchParams);let channel=str(b.channel||'global','channel',100),recipient=null;
  if(channel.startsWith('dm:')){const target=await one(db,'SELECT id FROM users WHERE handle=?',channel.slice(3));if(!target||target.id===user.id||await blocked(db,user.id,target.id))throw fail('This conversation is unavailable.',403);recipient=target.id;channel='dm:'+ [user.id,target.id].sort().join(':');}
  else if(channel.startsWith('group:'))await group(db,channel.slice(6),user,true);
  else if(channel.startsWith('tournament:')){const t=await one(db,"SELECT id FROM tournaments WHERE id=? AND status<>'Draft'",channel.slice(11));if(!t)throw fail('Tournament not found.',404);}
  else if(channel!=='global')throw fail('Unknown channel.');
  if(method==='GET')return {items:(await rows(db,`SELECT m.*,u.handle,p.display_name,p.avatar,p.color,p.font,p.font_url,p.country FROM messages m JOIN users u ON u.id=m.user_id JOIN profiles p ON p.user_id=u.id WHERE m.channel=? AND m.removed=0 AND NOT EXISTS(SELECT 1 FROM blocks WHERE (user_id=? AND target_id=m.user_id) OR(user_id=m.user_id AND target_id=?)) AND NOT EXISTS(SELECT 1 FROM mutes WHERE user_id=? AND target_id=m.user_id) ORDER BY m.created_at DESC LIMIT 50`,channel,user.id,user.id,user.id)).reverse()};
  if(method==='POST'){await run(db,'INSERT INTO messages VALUES(?,?,?,?,?,0,?)',id(),user.id,channel,recipient,str(b.content,'message',1500,true),now());if(recipient)await notify(db,recipient,`Message from @${user.handle}`,`/social/messages?to=${user.handle}`);return {ok:true};}}
 if(['/block','/mute'].includes(path)&&method==='POST'){requireUser(user);const b=await body(request),target=await one(db,'SELECT id FROM users WHERE handle=?',str(b.handle,'handle',24,true));if(!target||target.id===user.id)throw fail('Choose another player.');const table=path==='/block'?'blocks':'mutes';if(b.undo)await run(db,`DELETE FROM ${table} WHERE user_id=? AND target_id=?`,user.id,target.id);else await run(db,`INSERT OR IGNORE INTO ${table} VALUES(?,?)`,user.id,target.id);return {ok:true};}
 if(path==='/reports'&&method==='POST'){requireUser(user);const b=await body(request);await run(db,'INSERT INTO reports VALUES(?,?,?,?,?,?,?,?)',id(),user.id,choice(b.target_type,['player','post','message','clip','comment','thread'],'report type'),str(b.target_id,'target',100,true),choice(b.reason,['Spam','Harassment','Inappropriate content','Impersonation','Cheating allegation','Scam','Other'],'reason'),str(b.detail,'details',2000),'open',now());return {ok:true};}
 if(path==='/moderation'&&method==='GET'){staff(user,['moderator','editor','administrator']);return {reports:await rows(db,"SELECT * FROM reports WHERE status='open' ORDER BY created_at LIMIT 100"),logs:await rows(db,'SELECT * FROM moderation_logs ORDER BY created_at DESC LIMIT 100')};}
 if(path==='/moderation'&&method==='POST'){staff(user,['moderator','editor','administrator']);const b=await body(request),action=choice(b.action,['resolve','remove-post','remove-message','lock','pin','mute','suspend','ban','restore','remove-avatar','remove-banner','role','category'],'moderation action'),target=str(b.target,'target',100,true);
  if(action==='resolve')await run(db,"UPDATE reports SET status='resolved' WHERE id=?",target);
  else if(action==='remove-post')await run(db,'UPDATE posts SET removed=1 WHERE id IN (WITH RECURSIVE children(id) AS (SELECT id FROM posts WHERE id=? UNION ALL SELECT p.id FROM posts p JOIN children c ON p.parent_id=c.id) SELECT id FROM children) AND ? IS NOT NULL',target,target);
  else if(action==='remove-message')await run(db,'UPDATE messages SET removed=1 WHERE id=?',target);
  else if(action==='lock'||action==='pin')await run(db,`UPDATE posts SET ${action==='lock'?'locked':'pinned'}=? WHERE id=?`,b.undo?0:1,target);
  else if(action==='category')await run(db,'INSERT OR IGNORE INTO forum_categories VALUES(?)',str(target,'category',80,true));
  else {const p=await one(db,'SELECT * FROM users WHERE handle=?',target);if(!p)throw fail('Player not found.',404);if(p.id===user.id||p.role==='administrator')throw fail('This account cannot be changed here.',403);if(action==='role'){staff(user,['administrator']);await run(db,'UPDATE users SET role=? WHERE id=?',choice(b.role,['player','host','moderator','editor','administrator'],'role'),p.id);}else if(action.startsWith('remove-'))await run(db,`UPDATE profiles SET ${action==='remove-avatar'?'avatar':'banner'}='' WHERE user_id=?`,p.id);else {await db.batch([query(db,'UPDATE users SET status=? WHERE id=?',{mute:'muted',suspend:'suspended',ban:'banned',restore:'active'}[action],p.id),query(db,'DELETE FROM sessions WHERE user_id=?',p.id)]);}}
  await run(db,'INSERT INTO moderation_logs VALUES(?,?,?,?,?,?)',id(),user.id,action,target,str(b.detail,'audit note',1000),now());return {ok:true};}
 if(path==='/search'&&method==='GET'){const q=str(u.searchParams.get('q'),'search',80,true).replace(/^@/,'');return {players:await rows(db,`SELECT ${profileFields} FROM users u JOIN profiles p ON p.user_id=u.id WHERE (instr(lower(u.handle),lower(?))>0 OR instr(lower(p.display_name),lower(?))>0) AND u.status NOT IN ('banned','suspended') LIMIT 8`,q,q),groups:await rows(db,'SELECT id,name,handle FROM groups WHERE instr(lower(name),lower(?))>0 LIMIT 8',q),tournaments:await rows(db,"SELECT id,slug,title,game FROM tournaments WHERE (instr(lower(title),lower(?))>0 OR instr(lower(game),lower(?))>0) AND status<>'Draft' LIMIT 8",q,q),games:await rows(db,'SELECT * FROM games WHERE instr(lower(title),lower(?))>0 LIMIT 8',q),posts:await rows(db,`SELECT p.id,p.title,p.content,p.kind FROM posts p WHERE p.removed=0 AND (instr(lower(p.content),lower(?))>0 OR instr(lower(p.title),lower(?))>0) AND ${visibleGroup} LIMIT 12`,q,q,user?.id||'')};}
 return undefined;
}
