import {fail,id,now,one,run,read,rate} from './core.mjs';
import {requireUser} from './auth.mjs';
// Accept ordinary, self-contained MP4 only. Fragmented/live containers are
// rejected because their complete sample timelines cannot be bounded here.
export function mp4Duration(bytes){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let movie=false,ftyp=false,tracks=0,longest=0;
 function boxes(start,end,visit){let at=start;while(at<end){if(at+8>end)throw fail('Incomplete MP4 container.');let size=v.getUint32(at),head=8;const type=String.fromCharCode(...bytes.slice(at+4,at+8));if(size===1){if(at+16>end)throw fail('Invalid MP4.');const big=v.getBigUint64(at+8);if(big>BigInt(Number.MAX_SAFE_INTEGER))throw fail('Invalid MP4.');size=Number(big);head=16;}if(size===0)size=end-at;if(size<head||at+size>end)throw fail('Invalid MP4 box size.');visit(type,at+head,at+size);at+=size;}}
 function timeHeader(start,end){const version=v.getUint8(start),scaleAt=start+(version===1?20:12),durationAt=scaleAt+4;if(version>1||durationAt+(version?8:4)>end)throw fail('Invalid MP4 timeline.');const scale=v.getUint32(scaleAt),duration=version?Number(v.getBigUint64(durationAt)):v.getUint32(durationAt);if(!scale||!Number.isFinite(duration))throw fail('Invalid MP4 duration.');return {scale,duration:duration/scale};}
 boxes(0,bytes.length,(type,start,end)=>{if(type==='ftyp')ftyp=true;if(type==='moof')throw fail('Export a standard MP4 rather than a fragmented MP4.');if(type!=='moov')return;movie=true;boxes(start,end,(type,a,b)=>{if(type==='mvhd')longest=Math.max(longest,timeHeader(a,b).duration);if(type!=='trak')return;let scale=0,duration=0,samples=null,offset=0;boxes(a,b,(type,c,d)=>{if(type==='edts')boxes(c,d,(t,e,f)=>{if(t==='elst'){if(e+8>f||v.getUint32(e+4)>1)throw fail('Export this clip without a complex edit list.');}});if(type!=='mdia')return;boxes(c,d,(type,e,f)=>{if(type==='mdhd'){const h=timeHeader(e,f);scale=h.scale;duration=h.duration;}if(type!=='minf')return;boxes(e,f,(type,g,h)=>{if(type!=='stbl')return;boxes(g,h,(type,i,j)=>{if(type==='stts'){if(i+8>j)throw fail('Invalid MP4 timing.');const n=v.getUint32(i+4);if(n===0||i+8+n*8>j)throw fail('Invalid MP4 samples.');samples=0;for(let k=0;k<n;k++){const count=v.getUint32(i+8+k*8),delta=v.getUint32(i+12+k*8);if(!count||!delta)throw fail('Invalid sample timing.');samples+=count*delta;if(!Number.isSafeInteger(samples))throw fail('Invalid sample timing.');}}if(type==='ctts'){if(i+8>j)throw fail('Invalid composition timeline.');const version=v.getUint8(i),n=v.getUint32(i+4);if(version>1||i+8+n*8>j)throw fail('Invalid composition timeline.');for(let k=0;k<n;k++)offset=Math.max(offset,version?v.getInt32(i+12+k*8):v.getUint32(i+12+k*8));}});});});});if(!scale||samples===null)throw fail('MP4 must include a complete sample timeline.');tracks++;longest=Math.max(longest,duration,(samples+offset)/scale);});});
 if(!ftyp||!movie||!tracks||longest<=0)throw fail('Upload a valid MP4 video.');if(longest>45)throw fail('Clips must be 45 seconds or shorter.');return longest;}
function imageType(b){if(['GIF87a','GIF89a'].includes(String.fromCharCode(...b.slice(0,6)))&&b.length>=14)return 'image/gif';if(b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47)return 'image/png';if(b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)return 'image/jpeg';if(String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP')return 'image/webp';throw fail('Use a PNG, JPEG, GIF or WebP image.');}
export async function mediaRoute(request,env,path,user){const db=env.SOCIAL_DB;
 if(path==='/media'&&request.method==='POST'){requireUser(user,true);if(!env.MEDIA)throw fail('Uploads are not available yet. Please try again after storage is connected.',503);await rate(db,'upload:'+user.id,8,3600);const kind=new URL(request.url).searchParams.get('kind')==='clip'?'clip':'image',bytes=await read(request,kind==='clip'?20*1024*1024:4*1024*1024),mid=id();let mime,duration=null;if(kind==='clip'){duration=mp4Duration(bytes);mime='video/mp4';}else mime=imageType(bytes);await env.MEDIA.put(mid,bytes,{httpMetadata:{contentType:mime}});await run(db,'INSERT INTO media VALUES(?,?,?,?,?,?)',mid,user.id,kind,mime,new Uint8Array(0),now());return {url:'/api/social/media/'+mid,duration};}
 if(path.startsWith('/media/')&&request.method==='GET'){if(!env.MEDIA)throw fail('Media storage is unavailable.',503);const mid=path.split('/')[2],record=await one(db,'SELECT * FROM media WHERE id=?',mid);if(!record)throw fail('Media not found.',404);const link='/api/social/media/'+mid;const visible=record.user_id===user?.id||await one(db,"SELECT 1 FROM profiles p JOIN users u ON u.id=p.user_id WHERE (p.avatar=? OR p.banner=?) AND u.status NOT IN ('banned','suspended')",link,link)||await one(db,"SELECT 1 FROM posts p WHERE p.media=? AND p.removed=0 AND (p.group_id IS NULL OR EXISTS(SELECT 1 FROM groups g WHERE g.id=p.group_id AND (g.privacy='Public' OR EXISTS(SELECT 1 FROM group_members gm WHERE gm.group_id=g.id AND gm.user_id=? AND gm.status='accepted'))))",link,user?.id||'');if(!visible)throw fail('Media not found.',404);const object=await env.MEDIA.get(mid);if(!object)throw fail('Media not found.',404);return new Response(object.body,{headers:{'Content-Type':record.mime,'X-Content-Type-Options':'nosniff','Cache-Control':'private, max-age=60','Content-Security-Policy':"default-src 'none'; sandbox"}});}
 return undefined;
}
