import {announcementPhase,announceTournament} from './announcements.mjs';
import {fail,id,now,one,rows,run,query,body,str,num,choice,url,page,notify,notifyMany,secret} from './core.mjs';
import {requireUser,staff} from './auth.mjs';
import {FORMATS,settings,createBracket,result,nextRound,standings,propagate} from './brackets.mjs';
export const STATUSES=['Draft','Registration Open','Registration Closed','Check-In','Live','Completed','Cancelled'];
const unpack=r=>r?{...JSON.parse(r.data),...r,data:undefined}:null;
async function tournament(db,key,user){const t=unpack(await one(db,'SELECT * FROM tournaments WHERE id=? OR slug=?',key,key));if(!t||(t.status==='Draft'&&!canManage(user,t)))throw fail('Tournament not found.',404);return t;}
const canManage=(u,t)=>u&&(['editor','administrator'].includes(u.role)||(u.role==='host'&&t.owner_id===u.id));
function manage(u,t){requireUser(u);if(!canManage(u,t))throw fail('Only an assigned tournament host or editor can do this.',403);}
function date(v,label,required=false){const s=str(v,label,40,required);if(s&&(!/T.*(Z|[+-]\d\d:\d\d)$/.test(s)||!Number.isFinite(Date.parse(s))))throw fail(`${label} must include a valid timezone.`);return s;}
export function validateTournament(b){const title=str(b.title,'tournament name',120,true),slug=str(b.slug||title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),'slug',120,true);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))throw fail('Use lowercase letters, numbers and hyphens for the URL.');const timezone=str(b.timezone||'America/New_York','timezone',80);try{new Intl.DateTimeFormat('en',{timeZone:timezone});}catch{throw fail('Invalid timezone.');}const data={description:str(b.description,'description',5000),rules:str(b.rules,'rules',10000),start:date(b.start,'Start',true),end:date(b.end,'End'),registrationOpen:date(b.registrationOpen,'Registration opening'),registrationClose:date(b.registrationClose,'Registration closing'),min:Math.floor(num(b.min??2,'minimum players',2,128)),max:Math.floor(num(b.max??32,'maximum players',2,128)),region:str(b.region,'region',80),timezone,registration:choice(b.registration||'Open',['Open','Invite Code','Hybrid','Private'],'registration mode'),banner:url(b.banner),thumbnail:url(b.thumbnail),stream:url(b.stream),config:settings(b.config)};if(data.end&&Date.parse(data.end)<=Date.parse(data.start))throw fail('End must be after start.');if(data.min>data.max)throw fail('Minimum players cannot exceed maximum.');if(data.registrationOpen&&data.registrationClose&&data.registrationOpen>=data.registrationClose)throw fail('Registration must close after opening.');return {title,slug,game:str(b.game,'game',120,true),format:choice(b.format,FORMATS,'format'),status:choice(b.status||'Draft',STATUSES,'status'),...data};}
async function bracket(db,t){const b=await one(db,'SELECT * FROM brackets WHERE tournament_id=?',t.id);return b?{...JSON.parse(b.data),revision:b.revision}:null;}
async function saveBracket(db,t,s,revision){const mutation=id();const statements=[query(db,'UPDATE brackets SET data=?,revision=revision+1,mutation=? WHERE tournament_id=? AND revision=?',JSON.stringify(s),mutation,t.id,revision),query(db,'DELETE FROM matches WHERE tournament_id=? AND EXISTS(SELECT 1 FROM brackets WHERE tournament_id=? AND mutation=?)',t.id,t.id,mutation)];statements.push(query(db,"INSERT INTO matches(id,tournament_id,round,status,data) SELECT ? || ':' || json_extract(value,'$.id'),?,json_extract(value,'$.round'),json_extract(value,'$.status'),value FROM json_each(?) WHERE EXISTS(SELECT 1 FROM brackets WHERE tournament_id=? AND mutation=?)",t.id,t.id,JSON.stringify(s.matches),t.id,mutation));const r=await db.batch(statements);if(!r[0].meta.changes)throw fail('Another editor changed the bracket. Reload before saving.',409);return {...s,revision:revision+1};}
export async function tournamentRoute(request,env,path,user){const db=env.SOCIAL_DB,method=request.method,u=new URL(request.url);
 if(path==='/games'&&method==='GET')return {items:await rows(db,'SELECT * FROM games WHERE title LIKE ? ORDER BY title LIMIT 50','%'+str(u.searchParams.get('q'),'search',80)+'%')};
 if(path==='/games'&&method==='POST'){staff(user);const b=await body(request);await run(db,'INSERT INTO games VALUES(?,?,?,?,?,?)',id(),str(b.title,'game title',120,true),str(b.platform,'platform',80),str(b.genre,'genre',80),url(b.image),str(b.publisher,'publisher',100));return {ok:true};}
 if(path==='/tournaments'&&method==='GET'){const admin=u.searchParams.get('manage')==='1';if(admin)staff(user,['host','editor','administrator']);return {items:(await rows(db,`SELECT * FROM tournaments WHERE ${admin?(user.role==='host'?'owner_id=?':'1=1'):"status<>'Draft'"} ORDER BY created_at DESC LIMIT 30 OFFSET ?`,...(admin&&user.role==='host'?[user.id]:[]),page(u))).map(unpack)};}
 if(path==='/tournaments'&&method==='POST'){staff(user,['host','editor','administrator']);const input=await body(request),t=validateTournament(input);let owner=user.id;if(input.host){staff(user);const host=await one(db,"SELECT id FROM users WHERE handle=? AND role IN ('host','editor','administrator') AND status='active'",str(input.host,'host handle',24));if(!host)throw fail('Choose a player with a host or editor role.');owner=host.id;}const tid=id();try{const statements=[query(db,'INSERT INTO tournaments VALUES(?,?,?,?,?,?,?,?,1,?,?)',tid,t.slug,t.title,t.game,t.format,t.status,owner,JSON.stringify(t),now(),now())];const phase=announcementPhase(null,t.status);if(phase)statements.push(announceTournament(db,{...t,id:tid},phase));await db.batch(statements);}catch(e){if(String(e).includes('UNIQUE'))throw fail('That tournament URL is already used.',409);throw e;}return {id:tid,slug:t.slug};}
 const parts=path.split('/').filter(Boolean);if(parts[0]!=='tournaments'||!parts[1])return undefined;const t=await tournament(db,parts[1],user),action=parts[2];
 if(!action&&method==='GET'){const s=await bracket(db,t);return {tournament:t,bracket:s,standings:s?standings(s):[],players:await rows(db,"SELECT r.id,r.user_id,r.status,r.checked_in,r.seed,r.created_at,u.handle,p.display_name,p.avatar,p.gamertag FROM registrations r JOIN users u ON u.id=r.user_id JOIN profiles p ON p.user_id=u.id WHERE r.tournament_id=? AND r.status='approved' ORDER BY r.seed,r.created_at",t.id),registration:user?await one(db,'SELECT * FROM registrations WHERE tournament_id=? AND user_id=?',t.id,user.id):null,canManage:!!canManage(user,t)};}
 if(!action&&method==='PUT'){manage(user,t);const b=await body(request),v=validateTournament(b);if(t.format!==v.format&&await bracket(db,t))throw fail('Reset the bracket before changing format.');const statements=[query(db,'UPDATE tournaments SET title=?,slug=?,game=?,format=?,status=?,data=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?',v.title,v.slug,v.game,v.format,v.status,JSON.stringify(v),now(),t.id,num(b.revision,'revision',1))];const phase=announcementPhase(t.status,v.status);if(phase)statements.push(announceTournament(db,{...v,id:t.id},phase));const [r]=await db.batch(statements);if(!r.meta.changes)throw fail('Tournament changed. Reload before saving.',409);return {ok:true};}
 if(action==='register'&&method==='POST'){requireUser(user,true);const b=await body(request);if(t.status!=='Registration Open'||t.registration==='Private'||(t.registrationOpen&&now()<t.registrationOpen)||(t.registrationClose&&now()>t.registrationClose))throw fail('Registration is closed.');if(await one(db,'SELECT id FROM registrations WHERE tournament_id=? AND user_id=?',t.id,user.id))throw fail('You already have a registration for this tournament.',409);const code=str(b.code,'invite code',40).toUpperCase();let invite;if(code)invite=await one(db,'SELECT * FROM invite_codes WHERE code=? AND tournament_id=? AND enabled=1 AND (expires_at IS NULL OR expires_at>?) AND (max_uses IS NULL OR uses<max_uses)',code,t.id,now());if((code&&!invite)||(t.registration==='Invite Code'&&!invite))throw fail('A valid invitation code is required.');const rid=id(),status=invite?(invite.auto_approve?'approved':'pending'):'approved';const insert=query(db,`INSERT INTO registrations(id,tournament_id,user_id,status,created_at) SELECT ?,?,?,?,? WHERE (SELECT count(*) FROM registrations WHERE tournament_id=? AND status IN ('approved','pending')) < ? ${invite?"AND EXISTS(SELECT 1 FROM invite_codes WHERE id=? AND enabled=1 AND (expires_at IS NULL OR expires_at>?) AND (max_uses IS NULL OR uses<max_uses))":''}`,rid,t.id,user.id,status,now(),t.id,t.max,...(invite?[invite.id,now()]:[]));const queries=[insert];if(invite)queries.push(query(db,'UPDATE invite_codes SET uses=uses+1 WHERE id=? AND EXISTS(SELECT 1 FROM registrations WHERE id=?)',invite.id,rid));const r=await db.batch(queries);if(!r[0].meta.changes)throw fail('Tournament is full or this invitation is no longer available.',409);await notify(db,user.id,status==='approved'?'Tournament registration accepted':'Registration awaiting approval',`/social/tournaments/${t.slug}`);return {status};}
 if(action==='check-in'&&method==='POST'){requireUser(user);if(t.status!=='Check-In')throw fail('Check-in is not open.');await run(db,"UPDATE registrations SET checked_in=1 WHERE tournament_id=? AND user_id=? AND status='approved'",t.id,user.id);return {ok:true};}
 if(action==='submit-result'&&method==='POST'){requireUser(user,true);const b=await body(request),s=await bracket(db,t),m=s?.matches.find(m=>m.id===b.match);if(!m||!m.players.includes(user.id))throw fail('You are not assigned to that match.',403);await run(db,'INSERT INTO result_submissions VALUES(?,?,?,?,?,?,?,?)',id(),t.id,m.id,user.id,JSON.stringify({a:num(b.a??0,'score'),b:num(b.b??0,'score'),results:b.results||[],proof:url(b.proof)}),'Awaiting Verification',now());return {ok:true};}
 if(action==='registrations'&&method==='GET'){manage(user,t);return {items:await rows(db,'SELECT r.*,u.handle,p.display_name,p.gamertag FROM registrations r JOIN users u ON r.user_id=u.id JOIN profiles p ON p.user_id=u.id WHERE tournament_id=? ORDER BY seed,created_at LIMIT 128',t.id)};}
 if(action==='registrations'&&method==='POST'){manage(user,t);const activeBracket=await bracket(db,t);const b=await body(request),player=await one(db,'SELECT id FROM users WHERE handle=?',str(b.handle,'handle',24,true));if(!player)throw fail('No player has that handle.',404);const current=await one(db,'SELECT * FROM registrations WHERE tournament_id=? AND user_id=?',t.id,player.id);if(activeBracket&&(!current||b.seed&&Number(b.seed)!==current.seed))throw fail('Reset the bracket before changing seeds or adding players.');const status=choice(b.status||'approved',['approved','pending','rejected','banned','disqualified','no-show'],'player status');await run(db,'INSERT INTO registrations(id,tournament_id,user_id,status,checked_in,seed,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(tournament_id,user_id) DO UPDATE SET status=excluded.status,checked_in=excluded.checked_in,seed=excluded.seed',id(),t.id,player.id,status,b.checked_in?1:0,b.seed?Math.floor(num(b.seed,'seed',1,128)):null,now());if(activeBracket&&['disqualified','no-show','banned'].includes(status)){activeBracket.disqualified=[...new Set([...(activeBracket.disqualified||[]),player.id])];propagate(activeBracket);await saveBracket(db,t,activeBracket,activeBracket.revision);}await notify(db,player.id,'Your tournament registration was updated',`/social/tournaments/${t.slug}`);return {ok:true};}
 if(action==='invitations'){manage(user,t);if(method==='GET')return {items:await rows(db,'SELECT * FROM invite_codes WHERE tournament_id=? ORDER BY created_at DESC LIMIT 100',t.id)};if(method==='POST'){const b=await body(request);if(b.id){if(b.action==='delete')await run(db,'DELETE FROM invite_codes WHERE id=? AND tournament_id=?',b.id,t.id);else await run(db,'UPDATE invite_codes SET enabled=0 WHERE id=? AND tournament_id=?',b.id,t.id);return {ok:true};}const code='XBT-'+secret().slice(0,4).toUpperCase()+'-'+secret().slice(0,8).toUpperCase();await run(db,'INSERT INTO invite_codes VALUES(?,?,?,?,0,?,?,1,?)',id(),code,t.id,b.max_uses?Math.floor(num(b.max_uses,'maximum uses',1,10000)):null,date(b.expires_at,'Expiration')||null,b.auto_approve?1:0,now());return {code};}}
 if(action==='submissions'&&method==='GET'){manage(user,t);return {items:await rows(db,'SELECT * FROM result_submissions WHERE tournament_id=? ORDER BY created_at DESC LIMIT 100',t.id)};}
 if(action==='bracket'&&method==='POST'){manage(user,t);const b=await body(request),existing=await bracket(db,t);let s=existing;
  if(b.action==='generate'){if(existing?.locked)throw fail('Unlock the bracket first.');if(existing?.matches.some(m=>m.status==='Completed'&&!m.bye)&&!b.confirmReset)throw fail('Resetting removes recorded results. Confirm the reset.');let players=await rows(db,"SELECT r.user_id id,r.seed,p.display_name name,u.handle FROM registrations r JOIN profiles p ON r.user_id=p.user_id JOIN users u ON u.id=r.user_id WHERE tournament_id=? AND r.status='approved' ORDER BY r.seed IS NULL,r.seed,r.created_at",t.id);if(players.length<t.min||players.length>t.max)throw fail(`This tournament needs ${t.min}–${t.max} approved players.`);if(b.seeding==='random')for(let i=players.length-1;i>0;i--){const j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[players[i],players[j]]=[players[j],players[i]];}if(Array.isArray(b.order)){if(b.order.filter(Boolean).length!==players.length||new Set(b.order.filter(Boolean)).size!==players.length||b.order.some(id=>id&&!players.some(p=>p.id===id)))throw fail('Invalid seed order.');players=b.order.filter(Boolean).map(id=>players.find(p=>p.id===id));}players=players.map((p,i)=>({...p,seed:i+1}));s=createBracket(players,t.format,t.config,b.order||null);if(!existing){await run(db,'INSERT OR IGNORE INTO brackets VALUES(?,?,1,?)',t.id,JSON.stringify(s),id());s=await saveBracket(db,t,s,1);}else s=await saveBracket(db,t,s,num(b.revision,'revision',1));await notifyMany(db,s.matches.filter(m=>m.status==='Ready').flatMap(m=>m.players),'Your tournament match is assigned',`/social/tournaments/${t.slug}`);return {bracket:s};}
  if(!s)throw fail('Generate a bracket first.');const revision=num(b.revision,'revision',1);if(revision!==s.revision)throw fail('Bracket changed. Reload before saving.',409);
  if(b.action==='result'){s=result(s,str(b.match,'match',80,true),b);}
  else if(b.action==='reject'){await run(db,"UPDATE result_submissions SET status='Rejected' WHERE id=? AND tournament_id=?",b.submission,t.id);return {ok:true};}
  else if(b.action==='next')s=nextRound(s);
  else if(b.action==='lock')s.locked=true;
  else if(b.action==='unlock')s.locked=false;
  else if(b.action==='pause')s.paused=true;
  else if(b.action==='resume'||b.action==='start'){s.paused=false;s.locked=true;}
  else if(b.action==='complete'){if(!s.completed)throw fail('Finish all matches before completing the tournament.');}
  else if(b.action==='reset'){if(s.locked)throw fail('Unlock the bracket first.');if(!b.confirmReset)throw fail('Confirm resetting all results.');s=createBracket(s.players,t.format,t.config,s.slots);}
  else if(b.action==='match'){const m=s.matches.find(m=>m.id===b.match);if(!m)throw fail('Match not found.');Object.assign(m,{map:str(b.map,'map',100),mode:str(b.mode,'mode',100),notes:str(b.notes,'notes',1000),proof:url(b.proof),stream:url(b.stream),start:date(b.start,'Match start')});if(['Ready','Live','Disputed','Scheduled'].includes(b.status)&&m.players.filter(Boolean).length>=2&&m.status!=='Completed')m.status=b.status;}
  else throw fail('Unknown bracket action.');s=await saveBracket(db,t,s,revision);if(b.action==='result'&&b.submission)await run(db,"UPDATE result_submissions SET status='Confirmed' WHERE id=? AND tournament_id=?",b.submission,t.id);if(['start','complete'].includes(b.action)){const statements=[query(db,'UPDATE tournaments SET status=?,revision=revision+1,updated_at=? WHERE id=?',b.action==='start'?'Live':'Completed',now(),t.id)];if(b.action==='start')statements.push(announceTournament(db,t,'live'));await db.batch(statements);}if(['next','result'].includes(b.action))await notifyMany(db,b.action==='result'?(s.matches.find(m=>m.id===b.match)?.players||[]):s.players.map(p=>p.id),b.action==='start'?'Your tournament is starting':b.action==='result'?'Your match result was updated':'Your next tournament round is ready',`/social/tournaments/${t.slug}`);return {bracket:s};}
 return undefined;
}
