name = "xbtesports-calendar-public"
main = "calendar-public.mjs"
compatibility_date = "2026-09-12"
workers_dev = true

[[d1_databases]]
binding = "CALENDAR_DB"
database_name = "xbtesports-calendar"
database_id = "3c1e999c-31b1-44c6-80f9-84a6e7c5fa43"

[[d1_databases]]
binding = "SOCIAL_DB"
database_name = "xbtesports-social"
database_id = "977c2f9c-be13-41fb-97f4-a49b67cc9fe8"
